/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// NamespaceSliceLister helps list NamespaceSlices.
// All objects returned here must be treated as read-only.
type NamespaceSliceLister interface {
	// List lists all NamespaceSlices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.NamespaceSlice, err error)
	// NamespaceSlices returns an object that can list and get NamespaceSlices.
	NamespaceSlices(namespace string) NamespaceSliceNamespaceLister
	NamespaceSliceListerExpansion
}

// namespaceSliceLister implements the NamespaceSliceLister interface.
type namespaceSliceLister struct {
	indexer cache.Indexer
}

// NewNamespaceSliceLister returns a new NamespaceSliceLister.
func NewNamespaceSliceLister(indexer cache.Indexer) NamespaceSliceLister {
	return &namespaceSliceLister{indexer: indexer}
}

// List lists all NamespaceSlices in the indexer.
func (s *namespaceSliceLister) List(selector labels.Selector) (ret []*v1alpha2.NamespaceSlice, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.NamespaceSlice))
	})
	return ret, err
}

// NamespaceSlices returns an object that can list and get NamespaceSlices.
func (s *namespaceSliceLister) NamespaceSlices(namespace string) NamespaceSliceNamespaceLister {
	return namespaceSliceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// NamespaceSliceNamespaceLister helps list and get NamespaceSlices.
// All objects returned here must be treated as read-only.
type NamespaceSliceNamespaceLister interface {
	// List lists all NamespaceSlices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.NamespaceSlice, err error)
	// Get retrieves the NamespaceSlice from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.NamespaceSlice, error)
	NamespaceSliceNamespaceListerExpansion
}

// namespaceSliceNamespaceLister implements the NamespaceSliceNamespaceLister
// interface.
type namespaceSliceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all NamespaceSlices in the indexer for a given namespace.
func (s namespaceSliceNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.NamespaceSlice, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.NamespaceSlice))
	})
	return ret, err
}

// Get retrieves the NamespaceSlice from the indexer for a given namespace and name.
func (s namespaceSliceNamespaceLister) Get(name string) (*v1alpha2.NamespaceSlice, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("namespaceslice"), name)
	}
	return obj.(*v1alpha2.NamespaceSlice), nil
}
