/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubevaultv1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VaultRelayLister helps list VaultRelays.
// All objects returned here must be treated as read-only.
type VaultRelayLister interface {
	// List lists all VaultRelays in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubevaultv1alpha2.VaultRelay, err error)
	// VaultRelays returns an object that can list and get VaultRelays.
	VaultRelays(namespace string) VaultRelayNamespaceLister
	VaultRelayListerExpansion
}

// vaultRelayLister implements the VaultRelayLister interface.
type vaultRelayLister struct {
	listers.ResourceIndexer[*kubevaultv1alpha2.VaultRelay]
}

// NewVaultRelayLister returns a new VaultRelayLister.
func NewVaultRelayLister(indexer cache.Indexer) VaultRelayLister {
	return &vaultRelayLister{listers.New[*kubevaultv1alpha2.VaultRelay](indexer, kubevaultv1alpha2.Resource("vaultrelay"))}
}

// VaultRelays returns an object that can list and get VaultRelays.
func (s *vaultRelayLister) VaultRelays(namespace string) VaultRelayNamespaceLister {
	return vaultRelayNamespaceLister{listers.NewNamespaced[*kubevaultv1alpha2.VaultRelay](s.ResourceIndexer, namespace)}
}

// VaultRelayNamespaceLister helps list and get VaultRelays.
// All objects returned here must be treated as read-only.
type VaultRelayNamespaceLister interface {
	// List lists all VaultRelays in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubevaultv1alpha2.VaultRelay, err error)
	// Get retrieves the VaultRelay from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubevaultv1alpha2.VaultRelay, error)
	VaultRelayNamespaceListerExpansion
}

// vaultRelayNamespaceLister implements the VaultRelayNamespaceLister
// interface.
type vaultRelayNamespaceLister struct {
	listers.ResourceIndexer[*kubevaultv1alpha2.VaultRelay]
}
