/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	kubevaultv1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VaultServerLister helps list VaultServers.
// All objects returned here must be treated as read-only.
type VaultServerLister interface {
	// List lists all VaultServers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubevaultv1alpha2.VaultServer, err error)
	// VaultServers returns an object that can list and get VaultServers.
	VaultServers(namespace string) VaultServerNamespaceLister
	VaultServerListerExpansion
}

// vaultServerLister implements the VaultServerLister interface.
type vaultServerLister struct {
	listers.ResourceIndexer[*kubevaultv1alpha2.VaultServer]
}

// NewVaultServerLister returns a new VaultServerLister.
func NewVaultServerLister(indexer cache.Indexer) VaultServerLister {
	return &vaultServerLister{listers.New[*kubevaultv1alpha2.VaultServer](indexer, kubevaultv1alpha2.Resource("vaultserver"))}
}

// VaultServers returns an object that can list and get VaultServers.
func (s *vaultServerLister) VaultServers(namespace string) VaultServerNamespaceLister {
	return vaultServerNamespaceLister{listers.NewNamespaced[*kubevaultv1alpha2.VaultServer](s.ResourceIndexer, namespace)}
}

// VaultServerNamespaceLister helps list and get VaultServers.
// All objects returned here must be treated as read-only.
type VaultServerNamespaceLister interface {
	// List lists all VaultServers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*kubevaultv1alpha2.VaultServer, err error)
	// Get retrieves the VaultServer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*kubevaultv1alpha2.VaultServer, error)
	VaultServerNamespaceListerExpansion
}

// vaultServerNamespaceLister implements the VaultServerNamespaceLister
// interface.
type vaultServerNamespaceLister struct {
	listers.ResourceIndexer[*kubevaultv1alpha2.VaultServer]
}
