/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VaultRelayLister helps list VaultRelays.
// All objects returned here must be treated as read-only.
type VaultRelayLister interface {
	// List lists all VaultRelays in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.VaultRelay, err error)
	// VaultRelays returns an object that can list and get VaultRelays.
	VaultRelays(namespace string) VaultRelayNamespaceLister
	VaultRelayListerExpansion
}

// vaultRelayLister implements the VaultRelayLister interface.
type vaultRelayLister struct {
	indexer cache.Indexer
}

// NewVaultRelayLister returns a new VaultRelayLister.
func NewVaultRelayLister(indexer cache.Indexer) VaultRelayLister {
	return &vaultRelayLister{indexer: indexer}
}

// List lists all VaultRelays in the indexer.
func (s *vaultRelayLister) List(selector labels.Selector) (ret []*v1alpha2.VaultRelay, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.VaultRelay))
	})
	return ret, err
}

// VaultRelays returns an object that can list and get VaultRelays.
func (s *vaultRelayLister) VaultRelays(namespace string) VaultRelayNamespaceLister {
	return vaultRelayNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VaultRelayNamespaceLister helps list and get VaultRelays.
// All objects returned here must be treated as read-only.
type VaultRelayNamespaceLister interface {
	// List lists all VaultRelays in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.VaultRelay, err error)
	// Get retrieves the VaultRelay from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.VaultRelay, error)
	VaultRelayNamespaceListerExpansion
}

// vaultRelayNamespaceLister implements the VaultRelayNamespaceLister
// interface.
type vaultRelayNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VaultRelays in the indexer for a given namespace.
func (s vaultRelayNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.VaultRelay, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.VaultRelay))
	})
	return ret, err
}

// Get retrieves the VaultRelay from the indexer for a given namespace and name.
func (s vaultRelayNamespaceLister) Get(name string) (*v1alpha2.VaultRelay, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("vaultrelay"), name)
	}
	return obj.(*v1alpha2.VaultRelay), nil
}
