/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// VaultAgentLister helps list VaultAgents.
// All objects returned here must be treated as read-only.
type VaultAgentLister interface {
	// List lists all VaultAgents in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.VaultAgent, err error)
	// VaultAgents returns an object that can list and get VaultAgents.
	VaultAgents(namespace string) VaultAgentNamespaceLister
	VaultAgentListerExpansion
}

// vaultAgentLister implements the VaultAgentLister interface.
type vaultAgentLister struct {
	indexer cache.Indexer
}

// NewVaultAgentLister returns a new VaultAgentLister.
func NewVaultAgentLister(indexer cache.Indexer) VaultAgentLister {
	return &vaultAgentLister{indexer: indexer}
}

// List lists all VaultAgents in the indexer.
func (s *vaultAgentLister) List(selector labels.Selector) (ret []*v1alpha2.VaultAgent, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.VaultAgent))
	})
	return ret, err
}

// VaultAgents returns an object that can list and get VaultAgents.
func (s *vaultAgentLister) VaultAgents(namespace string) VaultAgentNamespaceLister {
	return vaultAgentNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// VaultAgentNamespaceLister helps list and get VaultAgents.
// All objects returned here must be treated as read-only.
type VaultAgentNamespaceLister interface {
	// List lists all VaultAgents in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.VaultAgent, err error)
	// Get retrieves the VaultAgent from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.VaultAgent, error)
	VaultAgentNamespaceListerExpansion
}

// vaultAgentNamespaceLister implements the VaultAgentNamespaceLister
// interface.
type vaultAgentNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all VaultAgents in the indexer for a given namespace.
func (s vaultAgentNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.VaultAgent, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.VaultAgent))
	})
	return ret, err
}

// Get retrieves the VaultAgent from the indexer for a given namespace and name.
func (s vaultAgentNamespaceLister) Get(name string) (*v1alpha2.VaultAgent, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("vaultagent"), name)
	}
	return obj.(*v1alpha2.VaultAgent), nil
}
