apiVersion: kubevault.com/v1alpha1
kind: VaultServer
metadata:
  name: exampleco
  namespace: demo
spec:
  nodes: 1
  version: "0.11.1"
  serviceTemplate:
    spec:
      type: NodePort
  backend:
    inmem: true
  unsealer:
    secretShares: 4
    secretThreshold: 2
    insecureTLS: true
    overwriteExisting: true
    mode:
      kubernetesSecret:
        secretName: vault-keys
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      port: 9102
      namespace: demo
      labels:
        app: vault
      interval: 10s
