/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIgniteRoles implements IgniteRoleInterface
type FakeIgniteRoles struct {
	Fake *FakeEngineV1alpha1
	ns   string
}

var igniterolesResource = v1alpha1.SchemeGroupVersion.WithResource("igniteroles")

var igniterolesKind = v1alpha1.SchemeGroupVersion.WithKind("IgniteRole")

// Get takes name of the igniteRole, and returns the corresponding igniteRole object, and an error if there is any.
func (c *FakeIgniteRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IgniteRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(igniterolesResource, c.ns, name), &v1alpha1.IgniteRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IgniteRole), err
}

// List takes label and field selectors, and returns the list of IgniteRoles that match those selectors.
func (c *FakeIgniteRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IgniteRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(igniterolesResource, igniterolesKind, c.ns, opts), &v1alpha1.IgniteRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IgniteRoleList{ListMeta: obj.(*v1alpha1.IgniteRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.IgniteRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested igniteRoles.
func (c *FakeIgniteRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(igniterolesResource, c.ns, opts))

}

// Create takes the representation of a igniteRole and creates it.  Returns the server's representation of the igniteRole, and an error, if there is any.
func (c *FakeIgniteRoles) Create(ctx context.Context, igniteRole *v1alpha1.IgniteRole, opts v1.CreateOptions) (result *v1alpha1.IgniteRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(igniterolesResource, c.ns, igniteRole), &v1alpha1.IgniteRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IgniteRole), err
}

// Update takes the representation of a igniteRole and updates it. Returns the server's representation of the igniteRole, and an error, if there is any.
func (c *FakeIgniteRoles) Update(ctx context.Context, igniteRole *v1alpha1.IgniteRole, opts v1.UpdateOptions) (result *v1alpha1.IgniteRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(igniterolesResource, c.ns, igniteRole), &v1alpha1.IgniteRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IgniteRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIgniteRoles) UpdateStatus(ctx context.Context, igniteRole *v1alpha1.IgniteRole, opts v1.UpdateOptions) (*v1alpha1.IgniteRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(igniterolesResource, "status", c.ns, igniteRole), &v1alpha1.IgniteRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IgniteRole), err
}

// Delete takes name of the igniteRole and deletes it. Returns an error if one occurs.
func (c *FakeIgniteRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(igniterolesResource, c.ns, name, opts), &v1alpha1.IgniteRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIgniteRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(igniterolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IgniteRoleList{})
	return err
}

// Patch applies the patch and returns the patched igniteRole.
func (c *FakeIgniteRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IgniteRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(igniterolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IgniteRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IgniteRole), err
}
