/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	enginev1alpha1 "kubevault.dev/apimachinery/client/clientset/versioned/typed/engine/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeDB2Roles implements DB2RoleInterface
type fakeDB2Roles struct {
	*gentype.FakeClientWithList[*v1alpha1.DB2Role, *v1alpha1.DB2RoleList]
	Fake *FakeEngineV1alpha1
}

func newFakeDB2Roles(fake *FakeEngineV1alpha1, namespace string) enginev1alpha1.DB2RoleInterface {
	return &fakeDB2Roles{
		gentype.NewFakeClientWithList[*v1alpha1.DB2Role, *v1alpha1.DB2RoleList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("db2roles"),
			v1alpha1.SchemeGroupVersion.WithKind("DB2Role"),
			func() *v1alpha1.DB2Role { return &v1alpha1.DB2Role{} },
			func() *v1alpha1.DB2RoleList { return &v1alpha1.DB2RoleList{} },
			func(dst, src *v1alpha1.DB2RoleList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.DB2RoleList) []*v1alpha1.DB2Role { return gentype.ToPointerSlice(list.Items) },
			func(list *v1alpha1.DB2RoleList, items []*v1alpha1.DB2Role) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
