/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMSSQLServerRoles implements MSSQLServerRoleInterface
type FakeMSSQLServerRoles struct {
	Fake *FakeEngineV1alpha1
	ns   string
}

var mssqlserverrolesResource = v1alpha1.SchemeGroupVersion.WithResource("mssqlserverroles")

var mssqlserverrolesKind = v1alpha1.SchemeGroupVersion.WithKind("MSSQLServerRole")

// Get takes name of the mSSQLServerRole, and returns the corresponding mSSQLServerRole object, and an error if there is any.
func (c *FakeMSSQLServerRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MSSQLServerRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(mssqlserverrolesResource, c.ns, name), &v1alpha1.MSSQLServerRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MSSQLServerRole), err
}

// List takes label and field selectors, and returns the list of MSSQLServerRoles that match those selectors.
func (c *FakeMSSQLServerRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MSSQLServerRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(mssqlserverrolesResource, mssqlserverrolesKind, c.ns, opts), &v1alpha1.MSSQLServerRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MSSQLServerRoleList{ListMeta: obj.(*v1alpha1.MSSQLServerRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MSSQLServerRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested mSSQLServerRoles.
func (c *FakeMSSQLServerRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(mssqlserverrolesResource, c.ns, opts))

}

// Create takes the representation of a mSSQLServerRole and creates it.  Returns the server's representation of the mSSQLServerRole, and an error, if there is any.
func (c *FakeMSSQLServerRoles) Create(ctx context.Context, mSSQLServerRole *v1alpha1.MSSQLServerRole, opts v1.CreateOptions) (result *v1alpha1.MSSQLServerRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(mssqlserverrolesResource, c.ns, mSSQLServerRole), &v1alpha1.MSSQLServerRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MSSQLServerRole), err
}

// Update takes the representation of a mSSQLServerRole and updates it. Returns the server's representation of the mSSQLServerRole, and an error, if there is any.
func (c *FakeMSSQLServerRoles) Update(ctx context.Context, mSSQLServerRole *v1alpha1.MSSQLServerRole, opts v1.UpdateOptions) (result *v1alpha1.MSSQLServerRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(mssqlserverrolesResource, c.ns, mSSQLServerRole), &v1alpha1.MSSQLServerRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MSSQLServerRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMSSQLServerRoles) UpdateStatus(ctx context.Context, mSSQLServerRole *v1alpha1.MSSQLServerRole, opts v1.UpdateOptions) (*v1alpha1.MSSQLServerRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(mssqlserverrolesResource, "status", c.ns, mSSQLServerRole), &v1alpha1.MSSQLServerRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MSSQLServerRole), err
}

// Delete takes name of the mSSQLServerRole and deletes it. Returns an error if one occurs.
func (c *FakeMSSQLServerRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(mssqlserverrolesResource, c.ns, name, opts), &v1alpha1.MSSQLServerRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMSSQLServerRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(mssqlserverrolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MSSQLServerRoleList{})
	return err
}

// Patch applies the patch and returns the patched mSSQLServerRole.
func (c *FakeMSSQLServerRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MSSQLServerRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(mssqlserverrolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MSSQLServerRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MSSQLServerRole), err
}
