/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubevault.dev/apimachinery/client/clientset/versioned/typed/engine/v1alpha1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeEngineV1alpha1 struct {
	*testing.Fake
}

func (c *FakeEngineV1alpha1) AWSRoles(namespace string) v1alpha1.AWSRoleInterface {
	return newFakeAWSRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) AzureRoles(namespace string) v1alpha1.AzureRoleInterface {
	return newFakeAzureRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) DB2Roles(namespace string) v1alpha1.DB2RoleInterface {
	return newFakeDB2Roles(c, namespace)
}

func (c *FakeEngineV1alpha1) DruidRoles(namespace string) v1alpha1.DruidRoleInterface {
	return newFakeDruidRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) ElasticsearchRoles(namespace string) v1alpha1.ElasticsearchRoleInterface {
	return newFakeElasticsearchRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) GCPRoles(namespace string) v1alpha1.GCPRoleInterface {
	return newFakeGCPRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) HanaDBRoles(namespace string) v1alpha1.HanaDBRoleInterface {
	return newFakeHanaDBRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) HazelcastRoles(namespace string) v1alpha1.HazelcastRoleInterface {
	return newFakeHazelcastRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) IgniteRoles(namespace string) v1alpha1.IgniteRoleInterface {
	return newFakeIgniteRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) KafkaRoles(namespace string) v1alpha1.KafkaRoleInterface {
	return newFakeKafkaRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MSSQLServerRoles(namespace string) v1alpha1.MSSQLServerRoleInterface {
	return newFakeMSSQLServerRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MariaDBRoles(namespace string) v1alpha1.MariaDBRoleInterface {
	return newFakeMariaDBRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MemcachedRoles(namespace string) v1alpha1.MemcachedRoleInterface {
	return newFakeMemcachedRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MilvusRoles(namespace string) v1alpha1.MilvusRoleInterface {
	return newFakeMilvusRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MongoDBRoles(namespace string) v1alpha1.MongoDBRoleInterface {
	return newFakeMongoDBRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) MySQLRoles(namespace string) v1alpha1.MySQLRoleInterface {
	return newFakeMySQLRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) Neo4jRoles(namespace string) v1alpha1.Neo4jRoleInterface {
	return newFakeNeo4jRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) OracleRoles(namespace string) v1alpha1.OracleRoleInterface {
	return newFakeOracleRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) PKIRoles(namespace string) v1alpha1.PKIRoleInterface {
	return newFakePKIRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) PostgresRoles(namespace string) v1alpha1.PostgresRoleInterface {
	return newFakePostgresRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) QdrantRoles(namespace string) v1alpha1.QdrantRoleInterface {
	return newFakeQdrantRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) RabbitMQRoles(namespace string) v1alpha1.RabbitMQRoleInterface {
	return newFakeRabbitMQRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) RedisRoles(namespace string) v1alpha1.RedisRoleInterface {
	return newFakeRedisRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) SecretAccessRequests(namespace string) v1alpha1.SecretAccessRequestInterface {
	return newFakeSecretAccessRequests(c, namespace)
}

func (c *FakeEngineV1alpha1) SecretEngines(namespace string) v1alpha1.SecretEngineInterface {
	return newFakeSecretEngines(c, namespace)
}

func (c *FakeEngineV1alpha1) SecretRoleBindings(namespace string) v1alpha1.SecretRoleBindingInterface {
	return newFakeSecretRoleBindings(c, namespace)
}

func (c *FakeEngineV1alpha1) SolrRoles(namespace string) v1alpha1.SolrRoleInterface {
	return newFakeSolrRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) WeaviateRoles(namespace string) v1alpha1.WeaviateRoleInterface {
	return newFakeWeaviateRoles(c, namespace)
}

func (c *FakeEngineV1alpha1) ZooKeeperRoles(namespace string) v1alpha1.ZooKeeperRoleInterface {
	return newFakeZooKeeperRoles(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeEngineV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
