/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeWeaviateRoles implements WeaviateRoleInterface
type FakeWeaviateRoles struct {
	Fake *FakeEngineV1alpha1
	ns   string
}

var weaviaterolesResource = v1alpha1.SchemeGroupVersion.WithResource("weaviateroles")

var weaviaterolesKind = v1alpha1.SchemeGroupVersion.WithKind("WeaviateRole")

// Get takes name of the weaviateRole, and returns the corresponding weaviateRole object, and an error if there is any.
func (c *FakeWeaviateRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WeaviateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(weaviaterolesResource, c.ns, name), &v1alpha1.WeaviateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateRole), err
}

// List takes label and field selectors, and returns the list of WeaviateRoles that match those selectors.
func (c *FakeWeaviateRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WeaviateRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(weaviaterolesResource, weaviaterolesKind, c.ns, opts), &v1alpha1.WeaviateRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.WeaviateRoleList{ListMeta: obj.(*v1alpha1.WeaviateRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.WeaviateRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested weaviateRoles.
func (c *FakeWeaviateRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(weaviaterolesResource, c.ns, opts))

}

// Create takes the representation of a weaviateRole and creates it.  Returns the server's representation of the weaviateRole, and an error, if there is any.
func (c *FakeWeaviateRoles) Create(ctx context.Context, weaviateRole *v1alpha1.WeaviateRole, opts v1.CreateOptions) (result *v1alpha1.WeaviateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(weaviaterolesResource, c.ns, weaviateRole), &v1alpha1.WeaviateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateRole), err
}

// Update takes the representation of a weaviateRole and updates it. Returns the server's representation of the weaviateRole, and an error, if there is any.
func (c *FakeWeaviateRoles) Update(ctx context.Context, weaviateRole *v1alpha1.WeaviateRole, opts v1.UpdateOptions) (result *v1alpha1.WeaviateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(weaviaterolesResource, c.ns, weaviateRole), &v1alpha1.WeaviateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeWeaviateRoles) UpdateStatus(ctx context.Context, weaviateRole *v1alpha1.WeaviateRole, opts v1.UpdateOptions) (*v1alpha1.WeaviateRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(weaviaterolesResource, "status", c.ns, weaviateRole), &v1alpha1.WeaviateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateRole), err
}

// Delete takes name of the weaviateRole and deletes it. Returns an error if one occurs.
func (c *FakeWeaviateRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(weaviaterolesResource, c.ns, name, opts), &v1alpha1.WeaviateRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeWeaviateRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(weaviaterolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.WeaviateRoleList{})
	return err
}

// Patch applies the patch and returns the patched weaviateRole.
func (c *FakeWeaviateRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WeaviateRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(weaviaterolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.WeaviateRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.WeaviateRole), err
}
