apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-operator
  template:
    metadata:
      labels:
        app: vault-operator
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${VAULT_OPERATOR_SERVICE_ACCOUNT}
      imagePullSecrets: [${VAULT_OPERATOR_IMAGE_PULL_SECRET}]
      containers:
      - name: operator
        image: ${VAULT_OPERATOR_DOCKER_REGISTRY}/vault-operator:${VAULT_OPERATOR_IMAGE_TAG}
        imagePullPolicy: ${VAULT_OPERATOR_IMAGE_PULL_POLICY}
        args:
        - run
        - --v=3
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-status-subresource=${VAULT_OPERATOR_ENABLE_STATUS_SUBRESOURCE}
        - --enable-analytics=${VAULT_OPERATOR_ENABLE_ANALYTICS}
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: vault-operator-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      priorityClassName: system-cluster-critical
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: vault-operator-apiserver-cert
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  ports:
  - name: admission
    port: 443
    targetPort: 8443
  selector:
    app: vault-operator
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.validators.kubevault.com
  labels:
    app: vault-operator
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: validators.kubevault.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: vault-operator
    namespace: ${VAULT_OPERATOR_NAMESPACE}
  version: v1alpha1
---
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.mutators.kubevault.com
  labels:
    app: vault-operator
spec:
  caBundle: ${SERVICE_SERVING_CERT_CA}
  group: mutators.kubevault.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: vault-operator
    namespace: ${VAULT_OPERATOR_NAMESPACE}
  version: v1alpha1
