apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-operator
  template:
    metadata:
      labels:
        app: vault-operator
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: ${VAULT_OPERATOR_SERVICE_ACCOUNT}
      imagePullSecrets: [${VAULT_OPERATOR_IMAGE_PULL_SECRET}]
      containers:
      - name: operator
        image: ${VAULT_OPERATOR_DOCKER_REGISTRY}/vault-operator:${VAULT_OPERATOR_IMAGE_TAG}
        imagePullPolicy: ${VAULT_OPERATOR_IMAGE_PULL_POLICY}
        args:
        - run
        - --v=3
        - --rbac=${VAULT_OPERATOR_ENABLE_RBAC}
        - --secure-port=8443
        - --audit-log-path=-
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --enable-analytics=${VAULT_OPERATOR_ENABLE_ANALYTICS}
        env:
          - name: VAULT_ADDR
            value: http://vault-server:8200
          - name: VAULT_TOKEN
            value: 3e4a5ba1-kube-422b-d1db-844979cab098
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/serving-cert
          name: serving-cert
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
      volumes:
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: vault-operator-apiserver-cert
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
---
# kube lacks the service serving cert signer, so provide a manual secret for it
apiVersion: v1
kind: Secret
metadata:
  name: vault-operator-apiserver-cert
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_SERVING_CERT}
  tls.key: ${TLS_SERVING_KEY}
---
# to be able to expose TSB inside the cluster
apiVersion: v1
kind: Service
metadata:
  name: vault-operator
  namespace: ${VAULT_OPERATOR_NAMESPACE}
  labels:
    app: vault-operator
spec:
  ports:
  - name: admission
    port: 443
    targetPort: 8443
  selector:
    app: vault-operator
