apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevault:core:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
- apiGroups:
  - kubevault.com
  - catalog.kubevault.com
  resources:
  - '*'
  verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevault:core:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.kubevault.com
  resources:
  - vaultserverversions
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevault:core:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - catalog.kubevault.com
  resources:
  - vaultserverversions
  verbs:
  - get
  - list
  - watch
