apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: vault
initializers:
  # the name needs to be fully qualified, i.e., containing at least two "."
  - name: vault.initializer.kubernetes.io
    rules:
      # apiGroups, apiVersion, resources all support wildcard "*".
      # "*" cannot be mixed with non-wildcard.
      - apiGroups:
          - ""
        apiVersions:
          - v1
        resources:
          - pods
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: vault-operator
  name: vault-operator
  namespace: vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-operator
    spec:
      containers:
      - name: operator
        args:
        - run
        - --v=3
        image: appscode/steward:canary
        ports:
        - containerPort: 56790
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: /etc/kubernetes
            name: cloudconfig
            readOnly: true
      volumes:
        - hostPath:
            path: /etc/kubernetes
          name: cloudconfig
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-operator
  name: vault-operator
  namespace: vault
spec:
  ports:
  - name: http
    port: 56790
    targetPort: http
  selector:
    app: vault-operator
