/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "kubevault.dev/apimachinery/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// AWSRoles returns a AWSRoleInformer.
	AWSRoles() AWSRoleInformer
	// AzureRoles returns a AzureRoleInformer.
	AzureRoles() AzureRoleInformer
	// DB2Roles returns a DB2RoleInformer.
	DB2Roles() DB2RoleInformer
	// DruidRoles returns a DruidRoleInformer.
	DruidRoles() DruidRoleInformer
	// ElasticsearchRoles returns a ElasticsearchRoleInformer.
	ElasticsearchRoles() ElasticsearchRoleInformer
	// GCPRoles returns a GCPRoleInformer.
	GCPRoles() GCPRoleInformer
	// HanaDBRoles returns a HanaDBRoleInformer.
	HanaDBRoles() HanaDBRoleInformer
	// HazelcastRoles returns a HazelcastRoleInformer.
	HazelcastRoles() HazelcastRoleInformer
	// IgniteRoles returns a IgniteRoleInformer.
	IgniteRoles() IgniteRoleInformer
	// KafkaRoles returns a KafkaRoleInformer.
	KafkaRoles() KafkaRoleInformer
	// MSSQLServerRoles returns a MSSQLServerRoleInformer.
	MSSQLServerRoles() MSSQLServerRoleInformer
	// MariaDBRoles returns a MariaDBRoleInformer.
	MariaDBRoles() MariaDBRoleInformer
	// MemcachedRoles returns a MemcachedRoleInformer.
	MemcachedRoles() MemcachedRoleInformer
	// MilvusRoles returns a MilvusRoleInformer.
	MilvusRoles() MilvusRoleInformer
	// MongoDBRoles returns a MongoDBRoleInformer.
	MongoDBRoles() MongoDBRoleInformer
	// MySQLRoles returns a MySQLRoleInformer.
	MySQLRoles() MySQLRoleInformer
	// Neo4jRoles returns a Neo4jRoleInformer.
	Neo4jRoles() Neo4jRoleInformer
	// OracleRoles returns a OracleRoleInformer.
	OracleRoles() OracleRoleInformer
	// PKIRoles returns a PKIRoleInformer.
	PKIRoles() PKIRoleInformer
	// PostgresRoles returns a PostgresRoleInformer.
	PostgresRoles() PostgresRoleInformer
	// QdrantRoles returns a QdrantRoleInformer.
	QdrantRoles() QdrantRoleInformer
	// RabbitMQRoles returns a RabbitMQRoleInformer.
	RabbitMQRoles() RabbitMQRoleInformer
	// RedisRoles returns a RedisRoleInformer.
	RedisRoles() RedisRoleInformer
	// SecretAccessRequests returns a SecretAccessRequestInformer.
	SecretAccessRequests() SecretAccessRequestInformer
	// SecretEngines returns a SecretEngineInformer.
	SecretEngines() SecretEngineInformer
	// SecretRoleBindings returns a SecretRoleBindingInformer.
	SecretRoleBindings() SecretRoleBindingInformer
	// SolrRoles returns a SolrRoleInformer.
	SolrRoles() SolrRoleInformer
	// WeaviateRoles returns a WeaviateRoleInformer.
	WeaviateRoles() WeaviateRoleInformer
	// ZooKeeperRoles returns a ZooKeeperRoleInformer.
	ZooKeeperRoles() ZooKeeperRoleInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// AWSRoles returns a AWSRoleInformer.
func (v *version) AWSRoles() AWSRoleInformer {
	return &aWSRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// AzureRoles returns a AzureRoleInformer.
func (v *version) AzureRoles() AzureRoleInformer {
	return &azureRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DB2Roles returns a DB2RoleInformer.
func (v *version) DB2Roles() DB2RoleInformer {
	return &dB2RoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// DruidRoles returns a DruidRoleInformer.
func (v *version) DruidRoles() DruidRoleInformer {
	return &druidRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ElasticsearchRoles returns a ElasticsearchRoleInformer.
func (v *version) ElasticsearchRoles() ElasticsearchRoleInformer {
	return &elasticsearchRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// GCPRoles returns a GCPRoleInformer.
func (v *version) GCPRoles() GCPRoleInformer {
	return &gCPRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HanaDBRoles returns a HanaDBRoleInformer.
func (v *version) HanaDBRoles() HanaDBRoleInformer {
	return &hanaDBRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// HazelcastRoles returns a HazelcastRoleInformer.
func (v *version) HazelcastRoles() HazelcastRoleInformer {
	return &hazelcastRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// IgniteRoles returns a IgniteRoleInformer.
func (v *version) IgniteRoles() IgniteRoleInformer {
	return &igniteRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// KafkaRoles returns a KafkaRoleInformer.
func (v *version) KafkaRoles() KafkaRoleInformer {
	return &kafkaRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MSSQLServerRoles returns a MSSQLServerRoleInformer.
func (v *version) MSSQLServerRoles() MSSQLServerRoleInformer {
	return &mSSQLServerRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MariaDBRoles returns a MariaDBRoleInformer.
func (v *version) MariaDBRoles() MariaDBRoleInformer {
	return &mariaDBRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MemcachedRoles returns a MemcachedRoleInformer.
func (v *version) MemcachedRoles() MemcachedRoleInformer {
	return &memcachedRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MilvusRoles returns a MilvusRoleInformer.
func (v *version) MilvusRoles() MilvusRoleInformer {
	return &milvusRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MongoDBRoles returns a MongoDBRoleInformer.
func (v *version) MongoDBRoles() MongoDBRoleInformer {
	return &mongoDBRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// MySQLRoles returns a MySQLRoleInformer.
func (v *version) MySQLRoles() MySQLRoleInformer {
	return &mySQLRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Neo4jRoles returns a Neo4jRoleInformer.
func (v *version) Neo4jRoles() Neo4jRoleInformer {
	return &neo4jRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// OracleRoles returns a OracleRoleInformer.
func (v *version) OracleRoles() OracleRoleInformer {
	return &oracleRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PKIRoles returns a PKIRoleInformer.
func (v *version) PKIRoles() PKIRoleInformer {
	return &pKIRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// PostgresRoles returns a PostgresRoleInformer.
func (v *version) PostgresRoles() PostgresRoleInformer {
	return &postgresRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// QdrantRoles returns a QdrantRoleInformer.
func (v *version) QdrantRoles() QdrantRoleInformer {
	return &qdrantRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RabbitMQRoles returns a RabbitMQRoleInformer.
func (v *version) RabbitMQRoles() RabbitMQRoleInformer {
	return &rabbitMQRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RedisRoles returns a RedisRoleInformer.
func (v *version) RedisRoles() RedisRoleInformer {
	return &redisRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SecretAccessRequests returns a SecretAccessRequestInformer.
func (v *version) SecretAccessRequests() SecretAccessRequestInformer {
	return &secretAccessRequestInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SecretEngines returns a SecretEngineInformer.
func (v *version) SecretEngines() SecretEngineInformer {
	return &secretEngineInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SecretRoleBindings returns a SecretRoleBindingInformer.
func (v *version) SecretRoleBindings() SecretRoleBindingInformer {
	return &secretRoleBindingInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SolrRoles returns a SolrRoleInformer.
func (v *version) SolrRoles() SolrRoleInformer {
	return &solrRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// WeaviateRoles returns a WeaviateRoleInformer.
func (v *version) WeaviateRoles() WeaviateRoleInformer {
	return &weaviateRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ZooKeeperRoles returns a ZooKeeperRoleInformer.
func (v *version) ZooKeeperRoles() ZooKeeperRoleInformer {
	return &zooKeeperRoleInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
