/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/catalog/v1alpha1"
	catalogv1alpha1 "kubevault.dev/apimachinery/client/clientset/versioned/typed/catalog/v1alpha1"

	gentype "k8s.io/client-go/gentype"
)

// fakeVaultServerVersions implements VaultServerVersionInterface
type fakeVaultServerVersions struct {
	*gentype.FakeClientWithList[*v1alpha1.VaultServerVersion, *v1alpha1.VaultServerVersionList]
	Fake *FakeCatalogV1alpha1
}

func newFakeVaultServerVersions(fake *FakeCatalogV1alpha1) catalogv1alpha1.VaultServerVersionInterface {
	return &fakeVaultServerVersions{
		gentype.NewFakeClientWithList[*v1alpha1.VaultServerVersion, *v1alpha1.VaultServerVersionList](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("vaultserverversions"),
			v1alpha1.SchemeGroupVersion.WithKind("VaultServerVersion"),
			func() *v1alpha1.VaultServerVersion { return &v1alpha1.VaultServerVersion{} },
			func() *v1alpha1.VaultServerVersionList { return &v1alpha1.VaultServerVersionList{} },
			func(dst, src *v1alpha1.VaultServerVersionList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.VaultServerVersionList) []*v1alpha1.VaultServerVersion {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.VaultServerVersionList, items []*v1alpha1.VaultServerVersion) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
