/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AWSRoleLister helps list AWSRoles.
// All objects returned here must be treated as read-only.
type AWSRoleLister interface {
	// List lists all AWSRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.AWSRole, err error)
	// AWSRoles returns an object that can list and get AWSRoles.
	AWSRoles(namespace string) AWSRoleNamespaceLister
	AWSRoleListerExpansion
}

// aWSRoleLister implements the AWSRoleLister interface.
type aWSRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.AWSRole]
}

// NewAWSRoleLister returns a new AWSRoleLister.
func NewAWSRoleLister(indexer cache.Indexer) AWSRoleLister {
	return &aWSRoleLister{listers.New[*enginev1alpha1.AWSRole](indexer, enginev1alpha1.Resource("awsrole"))}
}

// AWSRoles returns an object that can list and get AWSRoles.
func (s *aWSRoleLister) AWSRoles(namespace string) AWSRoleNamespaceLister {
	return aWSRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.AWSRole](s.ResourceIndexer, namespace)}
}

// AWSRoleNamespaceLister helps list and get AWSRoles.
// All objects returned here must be treated as read-only.
type AWSRoleNamespaceLister interface {
	// List lists all AWSRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.AWSRole, err error)
	// Get retrieves the AWSRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.AWSRole, error)
	AWSRoleNamespaceListerExpansion
}

// aWSRoleNamespaceLister implements the AWSRoleNamespaceLister
// interface.
type aWSRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.AWSRole]
}
