/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AzureRoleLister helps list AzureRoles.
// All objects returned here must be treated as read-only.
type AzureRoleLister interface {
	// List lists all AzureRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.AzureRole, err error)
	// AzureRoles returns an object that can list and get AzureRoles.
	AzureRoles(namespace string) AzureRoleNamespaceLister
	AzureRoleListerExpansion
}

// azureRoleLister implements the AzureRoleLister interface.
type azureRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.AzureRole]
}

// NewAzureRoleLister returns a new AzureRoleLister.
func NewAzureRoleLister(indexer cache.Indexer) AzureRoleLister {
	return &azureRoleLister{listers.New[*enginev1alpha1.AzureRole](indexer, enginev1alpha1.Resource("azurerole"))}
}

// AzureRoles returns an object that can list and get AzureRoles.
func (s *azureRoleLister) AzureRoles(namespace string) AzureRoleNamespaceLister {
	return azureRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.AzureRole](s.ResourceIndexer, namespace)}
}

// AzureRoleNamespaceLister helps list and get AzureRoles.
// All objects returned here must be treated as read-only.
type AzureRoleNamespaceLister interface {
	// List lists all AzureRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.AzureRole, err error)
	// Get retrieves the AzureRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.AzureRole, error)
	AzureRoleNamespaceListerExpansion
}

// azureRoleNamespaceLister implements the AzureRoleNamespaceLister
// interface.
type azureRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.AzureRole]
}
