/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// DB2RoleLister helps list DB2Roles.
// All objects returned here must be treated as read-only.
type DB2RoleLister interface {
	// List lists all DB2Roles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.DB2Role, err error)
	// DB2Roles returns an object that can list and get DB2Roles.
	DB2Roles(namespace string) DB2RoleNamespaceLister
	DB2RoleListerExpansion
}

// dB2RoleLister implements the DB2RoleLister interface.
type dB2RoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.DB2Role]
}

// NewDB2RoleLister returns a new DB2RoleLister.
func NewDB2RoleLister(indexer cache.Indexer) DB2RoleLister {
	return &dB2RoleLister{listers.New[*enginev1alpha1.DB2Role](indexer, enginev1alpha1.Resource("db2role"))}
}

// DB2Roles returns an object that can list and get DB2Roles.
func (s *dB2RoleLister) DB2Roles(namespace string) DB2RoleNamespaceLister {
	return dB2RoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.DB2Role](s.ResourceIndexer, namespace)}
}

// DB2RoleNamespaceLister helps list and get DB2Roles.
// All objects returned here must be treated as read-only.
type DB2RoleNamespaceLister interface {
	// List lists all DB2Roles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.DB2Role, err error)
	// Get retrieves the DB2Role from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.DB2Role, error)
	DB2RoleNamespaceListerExpansion
}

// dB2RoleNamespaceLister implements the DB2RoleNamespaceLister
// interface.
type dB2RoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.DB2Role]
}
