/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// EtcdRoleLister helps list EtcdRoles.
// All objects returned here must be treated as read-only.
type EtcdRoleLister interface {
	// List lists all EtcdRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.EtcdRole, err error)
	// EtcdRoles returns an object that can list and get EtcdRoles.
	EtcdRoles(namespace string) EtcdRoleNamespaceLister
	EtcdRoleListerExpansion
}

// etcdRoleLister implements the EtcdRoleLister interface.
type etcdRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.EtcdRole]
}

// NewEtcdRoleLister returns a new EtcdRoleLister.
func NewEtcdRoleLister(indexer cache.Indexer) EtcdRoleLister {
	return &etcdRoleLister{listers.New[*enginev1alpha1.EtcdRole](indexer, enginev1alpha1.Resource("etcdrole"))}
}

// EtcdRoles returns an object that can list and get EtcdRoles.
func (s *etcdRoleLister) EtcdRoles(namespace string) EtcdRoleNamespaceLister {
	return etcdRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.EtcdRole](s.ResourceIndexer, namespace)}
}

// EtcdRoleNamespaceLister helps list and get EtcdRoles.
// All objects returned here must be treated as read-only.
type EtcdRoleNamespaceLister interface {
	// List lists all EtcdRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.EtcdRole, err error)
	// Get retrieves the EtcdRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.EtcdRole, error)
	EtcdRoleNamespaceListerExpansion
}

// etcdRoleNamespaceLister implements the EtcdRoleNamespaceLister
// interface.
type etcdRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.EtcdRole]
}
