/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AWSRoleListerExpansion allows custom methods to be added to
// AWSRoleLister.
type AWSRoleListerExpansion interface{}

// AWSRoleNamespaceListerExpansion allows custom methods to be added to
// AWSRoleNamespaceLister.
type AWSRoleNamespaceListerExpansion interface{}

// AzureRoleListerExpansion allows custom methods to be added to
// AzureRoleLister.
type AzureRoleListerExpansion interface{}

// AzureRoleNamespaceListerExpansion allows custom methods to be added to
// AzureRoleNamespaceLister.
type AzureRoleNamespaceListerExpansion interface{}

// ElasticsearchRoleListerExpansion allows custom methods to be added to
// ElasticsearchRoleLister.
type ElasticsearchRoleListerExpansion interface{}

// ElasticsearchRoleNamespaceListerExpansion allows custom methods to be added to
// ElasticsearchRoleNamespaceLister.
type ElasticsearchRoleNamespaceListerExpansion interface{}

// GCPRoleListerExpansion allows custom methods to be added to
// GCPRoleLister.
type GCPRoleListerExpansion interface{}

// GCPRoleNamespaceListerExpansion allows custom methods to be added to
// GCPRoleNamespaceLister.
type GCPRoleNamespaceListerExpansion interface{}

// MongoDBRoleListerExpansion allows custom methods to be added to
// MongoDBRoleLister.
type MongoDBRoleListerExpansion interface{}

// MongoDBRoleNamespaceListerExpansion allows custom methods to be added to
// MongoDBRoleNamespaceLister.
type MongoDBRoleNamespaceListerExpansion interface{}

// MySQLRoleListerExpansion allows custom methods to be added to
// MySQLRoleLister.
type MySQLRoleListerExpansion interface{}

// MySQLRoleNamespaceListerExpansion allows custom methods to be added to
// MySQLRoleNamespaceLister.
type MySQLRoleNamespaceListerExpansion interface{}

// PostgresRoleListerExpansion allows custom methods to be added to
// PostgresRoleLister.
type PostgresRoleListerExpansion interface{}

// PostgresRoleNamespaceListerExpansion allows custom methods to be added to
// PostgresRoleNamespaceLister.
type PostgresRoleNamespaceListerExpansion interface{}

// SecretAccessRequestListerExpansion allows custom methods to be added to
// SecretAccessRequestLister.
type SecretAccessRequestListerExpansion interface{}

// SecretAccessRequestNamespaceListerExpansion allows custom methods to be added to
// SecretAccessRequestNamespaceLister.
type SecretAccessRequestNamespaceListerExpansion interface{}

// SecretEngineListerExpansion allows custom methods to be added to
// SecretEngineLister.
type SecretEngineListerExpansion interface{}

// SecretEngineNamespaceListerExpansion allows custom methods to be added to
// SecretEngineNamespaceLister.
type SecretEngineNamespaceListerExpansion interface{}

// SecretRoleBindingListerExpansion allows custom methods to be added to
// SecretRoleBindingLister.
type SecretRoleBindingListerExpansion interface{}

// SecretRoleBindingNamespaceListerExpansion allows custom methods to be added to
// SecretRoleBindingNamespaceLister.
type SecretRoleBindingNamespaceListerExpansion interface{}
