/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AWSRoleListerExpansion allows custom methods to be added to
// AWSRoleLister.
type AWSRoleListerExpansion interface{}

// AWSRoleNamespaceListerExpansion allows custom methods to be added to
// AWSRoleNamespaceLister.
type AWSRoleNamespaceListerExpansion interface{}

// AzureRoleListerExpansion allows custom methods to be added to
// AzureRoleLister.
type AzureRoleListerExpansion interface{}

// AzureRoleNamespaceListerExpansion allows custom methods to be added to
// AzureRoleNamespaceLister.
type AzureRoleNamespaceListerExpansion interface{}

// DB2RoleListerExpansion allows custom methods to be added to
// DB2RoleLister.
type DB2RoleListerExpansion interface{}

// DB2RoleNamespaceListerExpansion allows custom methods to be added to
// DB2RoleNamespaceLister.
type DB2RoleNamespaceListerExpansion interface{}

// DruidRoleListerExpansion allows custom methods to be added to
// DruidRoleLister.
type DruidRoleListerExpansion interface{}

// DruidRoleNamespaceListerExpansion allows custom methods to be added to
// DruidRoleNamespaceLister.
type DruidRoleNamespaceListerExpansion interface{}

// ElasticsearchRoleListerExpansion allows custom methods to be added to
// ElasticsearchRoleLister.
type ElasticsearchRoleListerExpansion interface{}

// ElasticsearchRoleNamespaceListerExpansion allows custom methods to be added to
// ElasticsearchRoleNamespaceLister.
type ElasticsearchRoleNamespaceListerExpansion interface{}

// GCPRoleListerExpansion allows custom methods to be added to
// GCPRoleLister.
type GCPRoleListerExpansion interface{}

// GCPRoleNamespaceListerExpansion allows custom methods to be added to
// GCPRoleNamespaceLister.
type GCPRoleNamespaceListerExpansion interface{}

// HanaDBRoleListerExpansion allows custom methods to be added to
// HanaDBRoleLister.
type HanaDBRoleListerExpansion interface{}

// HanaDBRoleNamespaceListerExpansion allows custom methods to be added to
// HanaDBRoleNamespaceLister.
type HanaDBRoleNamespaceListerExpansion interface{}

// HazelcastRoleListerExpansion allows custom methods to be added to
// HazelcastRoleLister.
type HazelcastRoleListerExpansion interface{}

// HazelcastRoleNamespaceListerExpansion allows custom methods to be added to
// HazelcastRoleNamespaceLister.
type HazelcastRoleNamespaceListerExpansion interface{}

// IgniteRoleListerExpansion allows custom methods to be added to
// IgniteRoleLister.
type IgniteRoleListerExpansion interface{}

// IgniteRoleNamespaceListerExpansion allows custom methods to be added to
// IgniteRoleNamespaceLister.
type IgniteRoleNamespaceListerExpansion interface{}

// KafkaRoleListerExpansion allows custom methods to be added to
// KafkaRoleLister.
type KafkaRoleListerExpansion interface{}

// KafkaRoleNamespaceListerExpansion allows custom methods to be added to
// KafkaRoleNamespaceLister.
type KafkaRoleNamespaceListerExpansion interface{}

// MSSQLServerRoleListerExpansion allows custom methods to be added to
// MSSQLServerRoleLister.
type MSSQLServerRoleListerExpansion interface{}

// MSSQLServerRoleNamespaceListerExpansion allows custom methods to be added to
// MSSQLServerRoleNamespaceLister.
type MSSQLServerRoleNamespaceListerExpansion interface{}

// MariaDBRoleListerExpansion allows custom methods to be added to
// MariaDBRoleLister.
type MariaDBRoleListerExpansion interface{}

// MariaDBRoleNamespaceListerExpansion allows custom methods to be added to
// MariaDBRoleNamespaceLister.
type MariaDBRoleNamespaceListerExpansion interface{}

// MemcachedRoleListerExpansion allows custom methods to be added to
// MemcachedRoleLister.
type MemcachedRoleListerExpansion interface{}

// MemcachedRoleNamespaceListerExpansion allows custom methods to be added to
// MemcachedRoleNamespaceLister.
type MemcachedRoleNamespaceListerExpansion interface{}

// MilvusRoleListerExpansion allows custom methods to be added to
// MilvusRoleLister.
type MilvusRoleListerExpansion interface{}

// MilvusRoleNamespaceListerExpansion allows custom methods to be added to
// MilvusRoleNamespaceLister.
type MilvusRoleNamespaceListerExpansion interface{}

// MongoDBRoleListerExpansion allows custom methods to be added to
// MongoDBRoleLister.
type MongoDBRoleListerExpansion interface{}

// MongoDBRoleNamespaceListerExpansion allows custom methods to be added to
// MongoDBRoleNamespaceLister.
type MongoDBRoleNamespaceListerExpansion interface{}

// MySQLRoleListerExpansion allows custom methods to be added to
// MySQLRoleLister.
type MySQLRoleListerExpansion interface{}

// MySQLRoleNamespaceListerExpansion allows custom methods to be added to
// MySQLRoleNamespaceLister.
type MySQLRoleNamespaceListerExpansion interface{}

// Neo4jRoleListerExpansion allows custom methods to be added to
// Neo4jRoleLister.
type Neo4jRoleListerExpansion interface{}

// Neo4jRoleNamespaceListerExpansion allows custom methods to be added to
// Neo4jRoleNamespaceLister.
type Neo4jRoleNamespaceListerExpansion interface{}

// OracleRoleListerExpansion allows custom methods to be added to
// OracleRoleLister.
type OracleRoleListerExpansion interface{}

// OracleRoleNamespaceListerExpansion allows custom methods to be added to
// OracleRoleNamespaceLister.
type OracleRoleNamespaceListerExpansion interface{}

// PKIRoleListerExpansion allows custom methods to be added to
// PKIRoleLister.
type PKIRoleListerExpansion interface{}

// PKIRoleNamespaceListerExpansion allows custom methods to be added to
// PKIRoleNamespaceLister.
type PKIRoleNamespaceListerExpansion interface{}

// PostgresRoleListerExpansion allows custom methods to be added to
// PostgresRoleLister.
type PostgresRoleListerExpansion interface{}

// PostgresRoleNamespaceListerExpansion allows custom methods to be added to
// PostgresRoleNamespaceLister.
type PostgresRoleNamespaceListerExpansion interface{}

// QdrantRoleListerExpansion allows custom methods to be added to
// QdrantRoleLister.
type QdrantRoleListerExpansion interface{}

// QdrantRoleNamespaceListerExpansion allows custom methods to be added to
// QdrantRoleNamespaceLister.
type QdrantRoleNamespaceListerExpansion interface{}

// RabbitMQRoleListerExpansion allows custom methods to be added to
// RabbitMQRoleLister.
type RabbitMQRoleListerExpansion interface{}

// RabbitMQRoleNamespaceListerExpansion allows custom methods to be added to
// RabbitMQRoleNamespaceLister.
type RabbitMQRoleNamespaceListerExpansion interface{}

// RedisRoleListerExpansion allows custom methods to be added to
// RedisRoleLister.
type RedisRoleListerExpansion interface{}

// RedisRoleNamespaceListerExpansion allows custom methods to be added to
// RedisRoleNamespaceLister.
type RedisRoleNamespaceListerExpansion interface{}

// SecretAccessRequestListerExpansion allows custom methods to be added to
// SecretAccessRequestLister.
type SecretAccessRequestListerExpansion interface{}

// SecretAccessRequestNamespaceListerExpansion allows custom methods to be added to
// SecretAccessRequestNamespaceLister.
type SecretAccessRequestNamespaceListerExpansion interface{}

// SecretEngineListerExpansion allows custom methods to be added to
// SecretEngineLister.
type SecretEngineListerExpansion interface{}

// SecretEngineNamespaceListerExpansion allows custom methods to be added to
// SecretEngineNamespaceLister.
type SecretEngineNamespaceListerExpansion interface{}

// SecretRoleBindingListerExpansion allows custom methods to be added to
// SecretRoleBindingLister.
type SecretRoleBindingListerExpansion interface{}

// SecretRoleBindingNamespaceListerExpansion allows custom methods to be added to
// SecretRoleBindingNamespaceLister.
type SecretRoleBindingNamespaceListerExpansion interface{}

// SolrRoleListerExpansion allows custom methods to be added to
// SolrRoleLister.
type SolrRoleListerExpansion interface{}

// SolrRoleNamespaceListerExpansion allows custom methods to be added to
// SolrRoleNamespaceLister.
type SolrRoleNamespaceListerExpansion interface{}

// WeaviateRoleListerExpansion allows custom methods to be added to
// WeaviateRoleLister.
type WeaviateRoleListerExpansion interface{}

// WeaviateRoleNamespaceListerExpansion allows custom methods to be added to
// WeaviateRoleNamespaceLister.
type WeaviateRoleNamespaceListerExpansion interface{}

// ZooKeeperRoleListerExpansion allows custom methods to be added to
// ZooKeeperRoleLister.
type ZooKeeperRoleListerExpansion interface{}

// ZooKeeperRoleNamespaceListerExpansion allows custom methods to be added to
// ZooKeeperRoleNamespaceLister.
type ZooKeeperRoleNamespaceListerExpansion interface{}
