/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// HanaDBRoleLister helps list HanaDBRoles.
// All objects returned here must be treated as read-only.
type HanaDBRoleLister interface {
	// List lists all HanaDBRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.HanaDBRole, err error)
	// HanaDBRoles returns an object that can list and get HanaDBRoles.
	HanaDBRoles(namespace string) HanaDBRoleNamespaceLister
	HanaDBRoleListerExpansion
}

// hanaDBRoleLister implements the HanaDBRoleLister interface.
type hanaDBRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.HanaDBRole]
}

// NewHanaDBRoleLister returns a new HanaDBRoleLister.
func NewHanaDBRoleLister(indexer cache.Indexer) HanaDBRoleLister {
	return &hanaDBRoleLister{listers.New[*enginev1alpha1.HanaDBRole](indexer, enginev1alpha1.Resource("hanadbrole"))}
}

// HanaDBRoles returns an object that can list and get HanaDBRoles.
func (s *hanaDBRoleLister) HanaDBRoles(namespace string) HanaDBRoleNamespaceLister {
	return hanaDBRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.HanaDBRole](s.ResourceIndexer, namespace)}
}

// HanaDBRoleNamespaceLister helps list and get HanaDBRoles.
// All objects returned here must be treated as read-only.
type HanaDBRoleNamespaceLister interface {
	// List lists all HanaDBRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.HanaDBRole, err error)
	// Get retrieves the HanaDBRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.HanaDBRole, error)
	HanaDBRoleNamespaceListerExpansion
}

// hanaDBRoleNamespaceLister implements the HanaDBRoleNamespaceLister
// interface.
type hanaDBRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.HanaDBRole]
}
