/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// HazelcastRoleLister helps list HazelcastRoles.
// All objects returned here must be treated as read-only.
type HazelcastRoleLister interface {
	// List lists all HazelcastRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HazelcastRole, err error)
	// HazelcastRoles returns an object that can list and get HazelcastRoles.
	HazelcastRoles(namespace string) HazelcastRoleNamespaceLister
	HazelcastRoleListerExpansion
}

// hazelcastRoleLister implements the HazelcastRoleLister interface.
type hazelcastRoleLister struct {
	indexer cache.Indexer
}

// NewHazelcastRoleLister returns a new HazelcastRoleLister.
func NewHazelcastRoleLister(indexer cache.Indexer) HazelcastRoleLister {
	return &hazelcastRoleLister{indexer: indexer}
}

// List lists all HazelcastRoles in the indexer.
func (s *hazelcastRoleLister) List(selector labels.Selector) (ret []*v1alpha1.HazelcastRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HazelcastRole))
	})
	return ret, err
}

// HazelcastRoles returns an object that can list and get HazelcastRoles.
func (s *hazelcastRoleLister) HazelcastRoles(namespace string) HazelcastRoleNamespaceLister {
	return hazelcastRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// HazelcastRoleNamespaceLister helps list and get HazelcastRoles.
// All objects returned here must be treated as read-only.
type HazelcastRoleNamespaceLister interface {
	// List lists all HazelcastRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.HazelcastRole, err error)
	// Get retrieves the HazelcastRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.HazelcastRole, error)
	HazelcastRoleNamespaceListerExpansion
}

// hazelcastRoleNamespaceLister implements the HazelcastRoleNamespaceLister
// interface.
type hazelcastRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all HazelcastRoles in the indexer for a given namespace.
func (s hazelcastRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.HazelcastRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.HazelcastRole))
	})
	return ret, err
}

// Get retrieves the HazelcastRole from the indexer for a given namespace and name.
func (s hazelcastRoleNamespaceLister) Get(name string) (*v1alpha1.HazelcastRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("hazelcastrole"), name)
	}
	return obj.(*v1alpha1.HazelcastRole), nil
}
