/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// IgniteRoleLister helps list IgniteRoles.
// All objects returned here must be treated as read-only.
type IgniteRoleLister interface {
	// List lists all IgniteRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IgniteRole, err error)
	// IgniteRoles returns an object that can list and get IgniteRoles.
	IgniteRoles(namespace string) IgniteRoleNamespaceLister
	IgniteRoleListerExpansion
}

// igniteRoleLister implements the IgniteRoleLister interface.
type igniteRoleLister struct {
	indexer cache.Indexer
}

// NewIgniteRoleLister returns a new IgniteRoleLister.
func NewIgniteRoleLister(indexer cache.Indexer) IgniteRoleLister {
	return &igniteRoleLister{indexer: indexer}
}

// List lists all IgniteRoles in the indexer.
func (s *igniteRoleLister) List(selector labels.Selector) (ret []*v1alpha1.IgniteRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IgniteRole))
	})
	return ret, err
}

// IgniteRoles returns an object that can list and get IgniteRoles.
func (s *igniteRoleLister) IgniteRoles(namespace string) IgniteRoleNamespaceLister {
	return igniteRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// IgniteRoleNamespaceLister helps list and get IgniteRoles.
// All objects returned here must be treated as read-only.
type IgniteRoleNamespaceLister interface {
	// List lists all IgniteRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.IgniteRole, err error)
	// Get retrieves the IgniteRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.IgniteRole, error)
	IgniteRoleNamespaceListerExpansion
}

// igniteRoleNamespaceLister implements the IgniteRoleNamespaceLister
// interface.
type igniteRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all IgniteRoles in the indexer for a given namespace.
func (s igniteRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.IgniteRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.IgniteRole))
	})
	return ret, err
}

// Get retrieves the IgniteRole from the indexer for a given namespace and name.
func (s igniteRoleNamespaceLister) Get(name string) (*v1alpha1.IgniteRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("igniterole"), name)
	}
	return obj.(*v1alpha1.IgniteRole), nil
}
