/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// KafkaRoleLister helps list KafkaRoles.
// All objects returned here must be treated as read-only.
type KafkaRoleLister interface {
	// List lists all KafkaRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KafkaRole, err error)
	// KafkaRoles returns an object that can list and get KafkaRoles.
	KafkaRoles(namespace string) KafkaRoleNamespaceLister
	KafkaRoleListerExpansion
}

// kafkaRoleLister implements the KafkaRoleLister interface.
type kafkaRoleLister struct {
	indexer cache.Indexer
}

// NewKafkaRoleLister returns a new KafkaRoleLister.
func NewKafkaRoleLister(indexer cache.Indexer) KafkaRoleLister {
	return &kafkaRoleLister{indexer: indexer}
}

// List lists all KafkaRoles in the indexer.
func (s *kafkaRoleLister) List(selector labels.Selector) (ret []*v1alpha1.KafkaRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KafkaRole))
	})
	return ret, err
}

// KafkaRoles returns an object that can list and get KafkaRoles.
func (s *kafkaRoleLister) KafkaRoles(namespace string) KafkaRoleNamespaceLister {
	return kafkaRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// KafkaRoleNamespaceLister helps list and get KafkaRoles.
// All objects returned here must be treated as read-only.
type KafkaRoleNamespaceLister interface {
	// List lists all KafkaRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.KafkaRole, err error)
	// Get retrieves the KafkaRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.KafkaRole, error)
	KafkaRoleNamespaceListerExpansion
}

// kafkaRoleNamespaceLister implements the KafkaRoleNamespaceLister
// interface.
type kafkaRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all KafkaRoles in the indexer for a given namespace.
func (s kafkaRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.KafkaRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.KafkaRole))
	})
	return ret, err
}

// Get retrieves the KafkaRole from the indexer for a given namespace and name.
func (s kafkaRoleNamespaceLister) Get(name string) (*v1alpha1.KafkaRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("kafkarole"), name)
	}
	return obj.(*v1alpha1.KafkaRole), nil
}
