/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MariaDBRoleLister helps list MariaDBRoles.
// All objects returned here must be treated as read-only.
type MariaDBRoleLister interface {
	// List lists all MariaDBRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MariaDBRole, err error)
	// MariaDBRoles returns an object that can list and get MariaDBRoles.
	MariaDBRoles(namespace string) MariaDBRoleNamespaceLister
	MariaDBRoleListerExpansion
}

// mariaDBRoleLister implements the MariaDBRoleLister interface.
type mariaDBRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MariaDBRole]
}

// NewMariaDBRoleLister returns a new MariaDBRoleLister.
func NewMariaDBRoleLister(indexer cache.Indexer) MariaDBRoleLister {
	return &mariaDBRoleLister{listers.New[*enginev1alpha1.MariaDBRole](indexer, enginev1alpha1.Resource("mariadbrole"))}
}

// MariaDBRoles returns an object that can list and get MariaDBRoles.
func (s *mariaDBRoleLister) MariaDBRoles(namespace string) MariaDBRoleNamespaceLister {
	return mariaDBRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.MariaDBRole](s.ResourceIndexer, namespace)}
}

// MariaDBRoleNamespaceLister helps list and get MariaDBRoles.
// All objects returned here must be treated as read-only.
type MariaDBRoleNamespaceLister interface {
	// List lists all MariaDBRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MariaDBRole, err error)
	// Get retrieves the MariaDBRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.MariaDBRole, error)
	MariaDBRoleNamespaceListerExpansion
}

// mariaDBRoleNamespaceLister implements the MariaDBRoleNamespaceLister
// interface.
type mariaDBRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MariaDBRole]
}
