/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MemcachedRoleLister helps list MemcachedRoles.
// All objects returned here must be treated as read-only.
type MemcachedRoleLister interface {
	// List lists all MemcachedRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MemcachedRole, err error)
	// MemcachedRoles returns an object that can list and get MemcachedRoles.
	MemcachedRoles(namespace string) MemcachedRoleNamespaceLister
	MemcachedRoleListerExpansion
}

// memcachedRoleLister implements the MemcachedRoleLister interface.
type memcachedRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MemcachedRole]
}

// NewMemcachedRoleLister returns a new MemcachedRoleLister.
func NewMemcachedRoleLister(indexer cache.Indexer) MemcachedRoleLister {
	return &memcachedRoleLister{listers.New[*enginev1alpha1.MemcachedRole](indexer, enginev1alpha1.Resource("memcachedrole"))}
}

// MemcachedRoles returns an object that can list and get MemcachedRoles.
func (s *memcachedRoleLister) MemcachedRoles(namespace string) MemcachedRoleNamespaceLister {
	return memcachedRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.MemcachedRole](s.ResourceIndexer, namespace)}
}

// MemcachedRoleNamespaceLister helps list and get MemcachedRoles.
// All objects returned here must be treated as read-only.
type MemcachedRoleNamespaceLister interface {
	// List lists all MemcachedRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MemcachedRole, err error)
	// Get retrieves the MemcachedRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.MemcachedRole, error)
	MemcachedRoleNamespaceListerExpansion
}

// memcachedRoleNamespaceLister implements the MemcachedRoleNamespaceLister
// interface.
type memcachedRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MemcachedRole]
}
