/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MilvusRoleLister helps list MilvusRoles.
// All objects returned here must be treated as read-only.
type MilvusRoleLister interface {
	// List lists all MilvusRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusRole, err error)
	// MilvusRoles returns an object that can list and get MilvusRoles.
	MilvusRoles(namespace string) MilvusRoleNamespaceLister
	MilvusRoleListerExpansion
}

// milvusRoleLister implements the MilvusRoleLister interface.
type milvusRoleLister struct {
	indexer cache.Indexer
}

// NewMilvusRoleLister returns a new MilvusRoleLister.
func NewMilvusRoleLister(indexer cache.Indexer) MilvusRoleLister {
	return &milvusRoleLister{indexer: indexer}
}

// List lists all MilvusRoles in the indexer.
func (s *milvusRoleLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusRole))
	})
	return ret, err
}

// MilvusRoles returns an object that can list and get MilvusRoles.
func (s *milvusRoleLister) MilvusRoles(namespace string) MilvusRoleNamespaceLister {
	return milvusRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MilvusRoleNamespaceLister helps list and get MilvusRoles.
// All objects returned here must be treated as read-only.
type MilvusRoleNamespaceLister interface {
	// List lists all MilvusRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.MilvusRole, err error)
	// Get retrieves the MilvusRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.MilvusRole, error)
	MilvusRoleNamespaceListerExpansion
}

// milvusRoleNamespaceLister implements the MilvusRoleNamespaceLister
// interface.
type milvusRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MilvusRoles in the indexer for a given namespace.
func (s milvusRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MilvusRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MilvusRole))
	})
	return ret, err
}

// Get retrieves the MilvusRole from the indexer for a given namespace and name.
func (s milvusRoleNamespaceLister) Get(name string) (*v1alpha1.MilvusRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("milvusrole"), name)
	}
	return obj.(*v1alpha1.MilvusRole), nil
}
