/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MSSQLServerRoleLister helps list MSSQLServerRoles.
// All objects returned here must be treated as read-only.
type MSSQLServerRoleLister interface {
	// List lists all MSSQLServerRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MSSQLServerRole, err error)
	// MSSQLServerRoles returns an object that can list and get MSSQLServerRoles.
	MSSQLServerRoles(namespace string) MSSQLServerRoleNamespaceLister
	MSSQLServerRoleListerExpansion
}

// mSSQLServerRoleLister implements the MSSQLServerRoleLister interface.
type mSSQLServerRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MSSQLServerRole]
}

// NewMSSQLServerRoleLister returns a new MSSQLServerRoleLister.
func NewMSSQLServerRoleLister(indexer cache.Indexer) MSSQLServerRoleLister {
	return &mSSQLServerRoleLister{listers.New[*enginev1alpha1.MSSQLServerRole](indexer, enginev1alpha1.Resource("mssqlserverrole"))}
}

// MSSQLServerRoles returns an object that can list and get MSSQLServerRoles.
func (s *mSSQLServerRoleLister) MSSQLServerRoles(namespace string) MSSQLServerRoleNamespaceLister {
	return mSSQLServerRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.MSSQLServerRole](s.ResourceIndexer, namespace)}
}

// MSSQLServerRoleNamespaceLister helps list and get MSSQLServerRoles.
// All objects returned here must be treated as read-only.
type MSSQLServerRoleNamespaceLister interface {
	// List lists all MSSQLServerRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MSSQLServerRole, err error)
	// Get retrieves the MSSQLServerRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.MSSQLServerRole, error)
	MSSQLServerRoleNamespaceListerExpansion
}

// mSSQLServerRoleNamespaceLister implements the MSSQLServerRoleNamespaceLister
// interface.
type mSSQLServerRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MSSQLServerRole]
}
