/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// MySQLRoleLister helps list MySQLRoles.
// All objects returned here must be treated as read-only.
type MySQLRoleLister interface {
	// List lists all MySQLRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MySQLRole, err error)
	// MySQLRoles returns an object that can list and get MySQLRoles.
	MySQLRoles(namespace string) MySQLRoleNamespaceLister
	MySQLRoleListerExpansion
}

// mySQLRoleLister implements the MySQLRoleLister interface.
type mySQLRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MySQLRole]
}

// NewMySQLRoleLister returns a new MySQLRoleLister.
func NewMySQLRoleLister(indexer cache.Indexer) MySQLRoleLister {
	return &mySQLRoleLister{listers.New[*enginev1alpha1.MySQLRole](indexer, enginev1alpha1.Resource("mysqlrole"))}
}

// MySQLRoles returns an object that can list and get MySQLRoles.
func (s *mySQLRoleLister) MySQLRoles(namespace string) MySQLRoleNamespaceLister {
	return mySQLRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.MySQLRole](s.ResourceIndexer, namespace)}
}

// MySQLRoleNamespaceLister helps list and get MySQLRoles.
// All objects returned here must be treated as read-only.
type MySQLRoleNamespaceLister interface {
	// List lists all MySQLRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.MySQLRole, err error)
	// Get retrieves the MySQLRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.MySQLRole, error)
	MySQLRoleNamespaceListerExpansion
}

// mySQLRoleNamespaceLister implements the MySQLRoleNamespaceLister
// interface.
type mySQLRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.MySQLRole]
}
