/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// Neo4jRoleLister helps list Neo4jRoles.
// All objects returned here must be treated as read-only.
type Neo4jRoleLister interface {
	// List lists all Neo4jRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.Neo4jRole, err error)
	// Neo4jRoles returns an object that can list and get Neo4jRoles.
	Neo4jRoles(namespace string) Neo4jRoleNamespaceLister
	Neo4jRoleListerExpansion
}

// neo4jRoleLister implements the Neo4jRoleLister interface.
type neo4jRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.Neo4jRole]
}

// NewNeo4jRoleLister returns a new Neo4jRoleLister.
func NewNeo4jRoleLister(indexer cache.Indexer) Neo4jRoleLister {
	return &neo4jRoleLister{listers.New[*enginev1alpha1.Neo4jRole](indexer, enginev1alpha1.Resource("neo4jrole"))}
}

// Neo4jRoles returns an object that can list and get Neo4jRoles.
func (s *neo4jRoleLister) Neo4jRoles(namespace string) Neo4jRoleNamespaceLister {
	return neo4jRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.Neo4jRole](s.ResourceIndexer, namespace)}
}

// Neo4jRoleNamespaceLister helps list and get Neo4jRoles.
// All objects returned here must be treated as read-only.
type Neo4jRoleNamespaceLister interface {
	// List lists all Neo4jRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.Neo4jRole, err error)
	// Get retrieves the Neo4jRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.Neo4jRole, error)
	Neo4jRoleNamespaceListerExpansion
}

// neo4jRoleNamespaceLister implements the Neo4jRoleNamespaceLister
// interface.
type neo4jRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.Neo4jRole]
}
