/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// OracleRoleLister helps list OracleRoles.
// All objects returned here must be treated as read-only.
type OracleRoleLister interface {
	// List lists all OracleRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.OracleRole, err error)
	// OracleRoles returns an object that can list and get OracleRoles.
	OracleRoles(namespace string) OracleRoleNamespaceLister
	OracleRoleListerExpansion
}

// oracleRoleLister implements the OracleRoleLister interface.
type oracleRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.OracleRole]
}

// NewOracleRoleLister returns a new OracleRoleLister.
func NewOracleRoleLister(indexer cache.Indexer) OracleRoleLister {
	return &oracleRoleLister{listers.New[*enginev1alpha1.OracleRole](indexer, enginev1alpha1.Resource("oraclerole"))}
}

// OracleRoles returns an object that can list and get OracleRoles.
func (s *oracleRoleLister) OracleRoles(namespace string) OracleRoleNamespaceLister {
	return oracleRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.OracleRole](s.ResourceIndexer, namespace)}
}

// OracleRoleNamespaceLister helps list and get OracleRoles.
// All objects returned here must be treated as read-only.
type OracleRoleNamespaceLister interface {
	// List lists all OracleRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.OracleRole, err error)
	// Get retrieves the OracleRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.OracleRole, error)
	OracleRoleNamespaceListerExpansion
}

// oracleRoleNamespaceLister implements the OracleRoleNamespaceLister
// interface.
type oracleRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.OracleRole]
}
