/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// OracleRoleLister helps list OracleRoles.
// All objects returned here must be treated as read-only.
type OracleRoleLister interface {
	// List lists all OracleRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OracleRole, err error)
	// OracleRoles returns an object that can list and get OracleRoles.
	OracleRoles(namespace string) OracleRoleNamespaceLister
	OracleRoleListerExpansion
}

// oracleRoleLister implements the OracleRoleLister interface.
type oracleRoleLister struct {
	indexer cache.Indexer
}

// NewOracleRoleLister returns a new OracleRoleLister.
func NewOracleRoleLister(indexer cache.Indexer) OracleRoleLister {
	return &oracleRoleLister{indexer: indexer}
}

// List lists all OracleRoles in the indexer.
func (s *oracleRoleLister) List(selector labels.Selector) (ret []*v1alpha1.OracleRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OracleRole))
	})
	return ret, err
}

// OracleRoles returns an object that can list and get OracleRoles.
func (s *oracleRoleLister) OracleRoles(namespace string) OracleRoleNamespaceLister {
	return oracleRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// OracleRoleNamespaceLister helps list and get OracleRoles.
// All objects returned here must be treated as read-only.
type OracleRoleNamespaceLister interface {
	// List lists all OracleRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.OracleRole, err error)
	// Get retrieves the OracleRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.OracleRole, error)
	OracleRoleNamespaceListerExpansion
}

// oracleRoleNamespaceLister implements the OracleRoleNamespaceLister
// interface.
type oracleRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all OracleRoles in the indexer for a given namespace.
func (s oracleRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.OracleRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.OracleRole))
	})
	return ret, err
}

// Get retrieves the OracleRole from the indexer for a given namespace and name.
func (s oracleRoleNamespaceLister) Get(name string) (*v1alpha1.OracleRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("oraclerole"), name)
	}
	return obj.(*v1alpha1.OracleRole), nil
}
