/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// PostgresRoleLister helps list PostgresRoles.
// All objects returned here must be treated as read-only.
type PostgresRoleLister interface {
	// List lists all PostgresRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.PostgresRole, err error)
	// PostgresRoles returns an object that can list and get PostgresRoles.
	PostgresRoles(namespace string) PostgresRoleNamespaceLister
	PostgresRoleListerExpansion
}

// postgresRoleLister implements the PostgresRoleLister interface.
type postgresRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.PostgresRole]
}

// NewPostgresRoleLister returns a new PostgresRoleLister.
func NewPostgresRoleLister(indexer cache.Indexer) PostgresRoleLister {
	return &postgresRoleLister{listers.New[*enginev1alpha1.PostgresRole](indexer, enginev1alpha1.Resource("postgresrole"))}
}

// PostgresRoles returns an object that can list and get PostgresRoles.
func (s *postgresRoleLister) PostgresRoles(namespace string) PostgresRoleNamespaceLister {
	return postgresRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.PostgresRole](s.ResourceIndexer, namespace)}
}

// PostgresRoleNamespaceLister helps list and get PostgresRoles.
// All objects returned here must be treated as read-only.
type PostgresRoleNamespaceLister interface {
	// List lists all PostgresRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.PostgresRole, err error)
	// Get retrieves the PostgresRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.PostgresRole, error)
	PostgresRoleNamespaceListerExpansion
}

// postgresRoleNamespaceLister implements the PostgresRoleNamespaceLister
// interface.
type postgresRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.PostgresRole]
}
