/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// QdrantRoleLister helps list QdrantRoles.
// All objects returned here must be treated as read-only.
type QdrantRoleLister interface {
	// List lists all QdrantRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.QdrantRole, err error)
	// QdrantRoles returns an object that can list and get QdrantRoles.
	QdrantRoles(namespace string) QdrantRoleNamespaceLister
	QdrantRoleListerExpansion
}

// qdrantRoleLister implements the QdrantRoleLister interface.
type qdrantRoleLister struct {
	indexer cache.Indexer
}

// NewQdrantRoleLister returns a new QdrantRoleLister.
func NewQdrantRoleLister(indexer cache.Indexer) QdrantRoleLister {
	return &qdrantRoleLister{indexer: indexer}
}

// List lists all QdrantRoles in the indexer.
func (s *qdrantRoleLister) List(selector labels.Selector) (ret []*v1alpha1.QdrantRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.QdrantRole))
	})
	return ret, err
}

// QdrantRoles returns an object that can list and get QdrantRoles.
func (s *qdrantRoleLister) QdrantRoles(namespace string) QdrantRoleNamespaceLister {
	return qdrantRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// QdrantRoleNamespaceLister helps list and get QdrantRoles.
// All objects returned here must be treated as read-only.
type QdrantRoleNamespaceLister interface {
	// List lists all QdrantRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.QdrantRole, err error)
	// Get retrieves the QdrantRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.QdrantRole, error)
	QdrantRoleNamespaceListerExpansion
}

// qdrantRoleNamespaceLister implements the QdrantRoleNamespaceLister
// interface.
type qdrantRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all QdrantRoles in the indexer for a given namespace.
func (s qdrantRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.QdrantRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.QdrantRole))
	})
	return ret, err
}

// Get retrieves the QdrantRole from the indexer for a given namespace and name.
func (s qdrantRoleNamespaceLister) Get(name string) (*v1alpha1.QdrantRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("qdrantrole"), name)
	}
	return obj.(*v1alpha1.QdrantRole), nil
}
