/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RabbitMQRoleLister helps list RabbitMQRoles.
// All objects returned here must be treated as read-only.
type RabbitMQRoleLister interface {
	// List lists all RabbitMQRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RabbitMQRole, err error)
	// RabbitMQRoles returns an object that can list and get RabbitMQRoles.
	RabbitMQRoles(namespace string) RabbitMQRoleNamespaceLister
	RabbitMQRoleListerExpansion
}

// rabbitMQRoleLister implements the RabbitMQRoleLister interface.
type rabbitMQRoleLister struct {
	indexer cache.Indexer
}

// NewRabbitMQRoleLister returns a new RabbitMQRoleLister.
func NewRabbitMQRoleLister(indexer cache.Indexer) RabbitMQRoleLister {
	return &rabbitMQRoleLister{indexer: indexer}
}

// List lists all RabbitMQRoles in the indexer.
func (s *rabbitMQRoleLister) List(selector labels.Selector) (ret []*v1alpha1.RabbitMQRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RabbitMQRole))
	})
	return ret, err
}

// RabbitMQRoles returns an object that can list and get RabbitMQRoles.
func (s *rabbitMQRoleLister) RabbitMQRoles(namespace string) RabbitMQRoleNamespaceLister {
	return rabbitMQRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RabbitMQRoleNamespaceLister helps list and get RabbitMQRoles.
// All objects returned here must be treated as read-only.
type RabbitMQRoleNamespaceLister interface {
	// List lists all RabbitMQRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RabbitMQRole, err error)
	// Get retrieves the RabbitMQRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RabbitMQRole, error)
	RabbitMQRoleNamespaceListerExpansion
}

// rabbitMQRoleNamespaceLister implements the RabbitMQRoleNamespaceLister
// interface.
type rabbitMQRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RabbitMQRoles in the indexer for a given namespace.
func (s rabbitMQRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.RabbitMQRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.RabbitMQRole))
	})
	return ret, err
}

// Get retrieves the RabbitMQRole from the indexer for a given namespace and name.
func (s rabbitMQRoleNamespaceLister) Get(name string) (*v1alpha1.RabbitMQRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("rabbitmqrole"), name)
	}
	return obj.(*v1alpha1.RabbitMQRole), nil
}
