/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RedisRoleLister helps list RedisRoles.
// All objects returned here must be treated as read-only.
type RedisRoleLister interface {
	// List lists all RedisRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.RedisRole, err error)
	// RedisRoles returns an object that can list and get RedisRoles.
	RedisRoles(namespace string) RedisRoleNamespaceLister
	RedisRoleListerExpansion
}

// redisRoleLister implements the RedisRoleLister interface.
type redisRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.RedisRole]
}

// NewRedisRoleLister returns a new RedisRoleLister.
func NewRedisRoleLister(indexer cache.Indexer) RedisRoleLister {
	return &redisRoleLister{listers.New[*enginev1alpha1.RedisRole](indexer, enginev1alpha1.Resource("redisrole"))}
}

// RedisRoles returns an object that can list and get RedisRoles.
func (s *redisRoleLister) RedisRoles(namespace string) RedisRoleNamespaceLister {
	return redisRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.RedisRole](s.ResourceIndexer, namespace)}
}

// RedisRoleNamespaceLister helps list and get RedisRoles.
// All objects returned here must be treated as read-only.
type RedisRoleNamespaceLister interface {
	// List lists all RedisRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.RedisRole, err error)
	// Get retrieves the RedisRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.RedisRole, error)
	RedisRoleNamespaceListerExpansion
}

// redisRoleNamespaceLister implements the RedisRoleNamespaceLister
// interface.
type redisRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.RedisRole]
}
