/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SolrRoleLister helps list SolrRoles.
// All objects returned here must be treated as read-only.
type SolrRoleLister interface {
	// List lists all SolrRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.SolrRole, err error)
	// SolrRoles returns an object that can list and get SolrRoles.
	SolrRoles(namespace string) SolrRoleNamespaceLister
	SolrRoleListerExpansion
}

// solrRoleLister implements the SolrRoleLister interface.
type solrRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.SolrRole]
}

// NewSolrRoleLister returns a new SolrRoleLister.
func NewSolrRoleLister(indexer cache.Indexer) SolrRoleLister {
	return &solrRoleLister{listers.New[*enginev1alpha1.SolrRole](indexer, enginev1alpha1.Resource("solrrole"))}
}

// SolrRoles returns an object that can list and get SolrRoles.
func (s *solrRoleLister) SolrRoles(namespace string) SolrRoleNamespaceLister {
	return solrRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.SolrRole](s.ResourceIndexer, namespace)}
}

// SolrRoleNamespaceLister helps list and get SolrRoles.
// All objects returned here must be treated as read-only.
type SolrRoleNamespaceLister interface {
	// List lists all SolrRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.SolrRole, err error)
	// Get retrieves the SolrRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.SolrRole, error)
	SolrRoleNamespaceListerExpansion
}

// solrRoleNamespaceLister implements the SolrRoleNamespaceLister
// interface.
type solrRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.SolrRole]
}
