/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WeaviateRoleLister helps list WeaviateRoles.
// All objects returned here must be treated as read-only.
type WeaviateRoleLister interface {
	// List lists all WeaviateRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.WeaviateRole, err error)
	// WeaviateRoles returns an object that can list and get WeaviateRoles.
	WeaviateRoles(namespace string) WeaviateRoleNamespaceLister
	WeaviateRoleListerExpansion
}

// weaviateRoleLister implements the WeaviateRoleLister interface.
type weaviateRoleLister struct {
	listers.ResourceIndexer[*enginev1alpha1.WeaviateRole]
}

// NewWeaviateRoleLister returns a new WeaviateRoleLister.
func NewWeaviateRoleLister(indexer cache.Indexer) WeaviateRoleLister {
	return &weaviateRoleLister{listers.New[*enginev1alpha1.WeaviateRole](indexer, enginev1alpha1.Resource("weaviaterole"))}
}

// WeaviateRoles returns an object that can list and get WeaviateRoles.
func (s *weaviateRoleLister) WeaviateRoles(namespace string) WeaviateRoleNamespaceLister {
	return weaviateRoleNamespaceLister{listers.NewNamespaced[*enginev1alpha1.WeaviateRole](s.ResourceIndexer, namespace)}
}

// WeaviateRoleNamespaceLister helps list and get WeaviateRoles.
// All objects returned here must be treated as read-only.
type WeaviateRoleNamespaceLister interface {
	// List lists all WeaviateRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*enginev1alpha1.WeaviateRole, err error)
	// Get retrieves the WeaviateRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*enginev1alpha1.WeaviateRole, error)
	WeaviateRoleNamespaceListerExpansion
}

// weaviateRoleNamespaceLister implements the WeaviateRoleNamespaceLister
// interface.
type weaviateRoleNamespaceLister struct {
	listers.ResourceIndexer[*enginev1alpha1.WeaviateRole]
}
