/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// ZooKeeperRoleLister helps list ZooKeeperRoles.
// All objects returned here must be treated as read-only.
type ZooKeeperRoleLister interface {
	// List lists all ZooKeeperRoles in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ZooKeeperRole, err error)
	// ZooKeeperRoles returns an object that can list and get ZooKeeperRoles.
	ZooKeeperRoles(namespace string) ZooKeeperRoleNamespaceLister
	ZooKeeperRoleListerExpansion
}

// zooKeeperRoleLister implements the ZooKeeperRoleLister interface.
type zooKeeperRoleLister struct {
	indexer cache.Indexer
}

// NewZooKeeperRoleLister returns a new ZooKeeperRoleLister.
func NewZooKeeperRoleLister(indexer cache.Indexer) ZooKeeperRoleLister {
	return &zooKeeperRoleLister{indexer: indexer}
}

// List lists all ZooKeeperRoles in the indexer.
func (s *zooKeeperRoleLister) List(selector labels.Selector) (ret []*v1alpha1.ZooKeeperRole, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ZooKeeperRole))
	})
	return ret, err
}

// ZooKeeperRoles returns an object that can list and get ZooKeeperRoles.
func (s *zooKeeperRoleLister) ZooKeeperRoles(namespace string) ZooKeeperRoleNamespaceLister {
	return zooKeeperRoleNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// ZooKeeperRoleNamespaceLister helps list and get ZooKeeperRoles.
// All objects returned here must be treated as read-only.
type ZooKeeperRoleNamespaceLister interface {
	// List lists all ZooKeeperRoles in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ZooKeeperRole, err error)
	// Get retrieves the ZooKeeperRole from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ZooKeeperRole, error)
	ZooKeeperRoleNamespaceListerExpansion
}

// zooKeeperRoleNamespaceLister implements the ZooKeeperRoleNamespaceLister
// interface.
type zooKeeperRoleNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all ZooKeeperRoles in the indexer for a given namespace.
func (s zooKeeperRoleNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.ZooKeeperRole, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.ZooKeeperRole))
	})
	return ret, err
}

// Get retrieves the ZooKeeperRole from the indexer for a given namespace and name.
func (s zooKeeperRoleNamespaceLister) Get(name string) (*v1alpha1.ZooKeeperRole, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("zookeeperrole"), name)
	}
	return obj.(*v1alpha1.ZooKeeperRole), nil
}
