/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DB2RolesGetter has a method to return a DB2RoleInterface.
// A group's client should implement this interface.
type DB2RolesGetter interface {
	DB2Roles(namespace string) DB2RoleInterface
}

// DB2RoleInterface has methods to work with DB2Role resources.
type DB2RoleInterface interface {
	Create(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.CreateOptions) (*v1alpha1.DB2Role, error)
	Update(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.UpdateOptions) (*v1alpha1.DB2Role, error)
	UpdateStatus(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.UpdateOptions) (*v1alpha1.DB2Role, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DB2Role, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DB2RoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DB2Role, err error)
	DB2RoleExpansion
}

// dB2Roles implements DB2RoleInterface
type dB2Roles struct {
	client rest.Interface
	ns     string
}

// newDB2Roles returns a DB2Roles
func newDB2Roles(c *EngineV1alpha1Client, namespace string) *dB2Roles {
	return &dB2Roles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the dB2Role, and returns the corresponding dB2Role object, and an error if there is any.
func (c *dB2Roles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DB2Role, err error) {
	result = &v1alpha1.DB2Role{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("db2roles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DB2Roles that match those selectors.
func (c *dB2Roles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DB2RoleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DB2RoleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("db2roles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dB2Roles.
func (c *dB2Roles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("db2roles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dB2Role and creates it.  Returns the server's representation of the dB2Role, and an error, if there is any.
func (c *dB2Roles) Create(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.CreateOptions) (result *v1alpha1.DB2Role, err error) {
	result = &v1alpha1.DB2Role{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("db2roles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dB2Role).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dB2Role and updates it. Returns the server's representation of the dB2Role, and an error, if there is any.
func (c *dB2Roles) Update(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.UpdateOptions) (result *v1alpha1.DB2Role, err error) {
	result = &v1alpha1.DB2Role{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("db2roles").
		Name(dB2Role.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dB2Role).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *dB2Roles) UpdateStatus(ctx context.Context, dB2Role *v1alpha1.DB2Role, opts v1.UpdateOptions) (result *v1alpha1.DB2Role, err error) {
	result = &v1alpha1.DB2Role{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("db2roles").
		Name(dB2Role.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dB2Role).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dB2Role and deletes it. Returns an error if one occurs.
func (c *dB2Roles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("db2roles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dB2Roles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("db2roles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dB2Role.
func (c *dB2Roles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DB2Role, err error) {
	result = &v1alpha1.DB2Role{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("db2roles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
