/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"net/http"

	v1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	"kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type EngineV1alpha1Interface interface {
	RESTClient() rest.Interface
	AWSRolesGetter
	AzureRolesGetter
	DB2RolesGetter
	DruidRolesGetter
	ElasticsearchRolesGetter
	GCPRolesGetter
	HanaDBRolesGetter
	HazelcastRolesGetter
	IgniteRolesGetter
	KafkaRolesGetter
	MSSQLServerRolesGetter
	MariaDBRolesGetter
	MemcachedRolesGetter
	MilvusRolesGetter
	MongoDBRolesGetter
	MySQLRolesGetter
	Neo4jRolesGetter
	OracleRolesGetter
	PKIRolesGetter
	PostgresRolesGetter
	QdrantRolesGetter
	RabbitMQRolesGetter
	RedisRolesGetter
	SecretAccessRequestsGetter
	SecretEnginesGetter
	SecretRoleBindingsGetter
	SolrRolesGetter
	WeaviateRolesGetter
	ZooKeeperRolesGetter
}

// EngineV1alpha1Client is used to interact with features provided by the engine.kubevault.com group.
type EngineV1alpha1Client struct {
	restClient rest.Interface
}

func (c *EngineV1alpha1Client) AWSRoles(namespace string) AWSRoleInterface {
	return newAWSRoles(c, namespace)
}

func (c *EngineV1alpha1Client) AzureRoles(namespace string) AzureRoleInterface {
	return newAzureRoles(c, namespace)
}

func (c *EngineV1alpha1Client) DB2Roles(namespace string) DB2RoleInterface {
	return newDB2Roles(c, namespace)
}

func (c *EngineV1alpha1Client) DruidRoles(namespace string) DruidRoleInterface {
	return newDruidRoles(c, namespace)
}

func (c *EngineV1alpha1Client) ElasticsearchRoles(namespace string) ElasticsearchRoleInterface {
	return newElasticsearchRoles(c, namespace)
}

func (c *EngineV1alpha1Client) GCPRoles(namespace string) GCPRoleInterface {
	return newGCPRoles(c, namespace)
}

func (c *EngineV1alpha1Client) HanaDBRoles(namespace string) HanaDBRoleInterface {
	return newHanaDBRoles(c, namespace)
}

func (c *EngineV1alpha1Client) HazelcastRoles(namespace string) HazelcastRoleInterface {
	return newHazelcastRoles(c, namespace)
}

func (c *EngineV1alpha1Client) IgniteRoles(namespace string) IgniteRoleInterface {
	return newIgniteRoles(c, namespace)
}

func (c *EngineV1alpha1Client) KafkaRoles(namespace string) KafkaRoleInterface {
	return newKafkaRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MSSQLServerRoles(namespace string) MSSQLServerRoleInterface {
	return newMSSQLServerRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MariaDBRoles(namespace string) MariaDBRoleInterface {
	return newMariaDBRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MemcachedRoles(namespace string) MemcachedRoleInterface {
	return newMemcachedRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MilvusRoles(namespace string) MilvusRoleInterface {
	return newMilvusRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MongoDBRoles(namespace string) MongoDBRoleInterface {
	return newMongoDBRoles(c, namespace)
}

func (c *EngineV1alpha1Client) MySQLRoles(namespace string) MySQLRoleInterface {
	return newMySQLRoles(c, namespace)
}

func (c *EngineV1alpha1Client) Neo4jRoles(namespace string) Neo4jRoleInterface {
	return newNeo4jRoles(c, namespace)
}

func (c *EngineV1alpha1Client) OracleRoles(namespace string) OracleRoleInterface {
	return newOracleRoles(c, namespace)
}

func (c *EngineV1alpha1Client) PKIRoles(namespace string) PKIRoleInterface {
	return newPKIRoles(c, namespace)
}

func (c *EngineV1alpha1Client) PostgresRoles(namespace string) PostgresRoleInterface {
	return newPostgresRoles(c, namespace)
}

func (c *EngineV1alpha1Client) QdrantRoles(namespace string) QdrantRoleInterface {
	return newQdrantRoles(c, namespace)
}

func (c *EngineV1alpha1Client) RabbitMQRoles(namespace string) RabbitMQRoleInterface {
	return newRabbitMQRoles(c, namespace)
}

func (c *EngineV1alpha1Client) RedisRoles(namespace string) RedisRoleInterface {
	return newRedisRoles(c, namespace)
}

func (c *EngineV1alpha1Client) SecretAccessRequests(namespace string) SecretAccessRequestInterface {
	return newSecretAccessRequests(c, namespace)
}

func (c *EngineV1alpha1Client) SecretEngines(namespace string) SecretEngineInterface {
	return newSecretEngines(c, namespace)
}

func (c *EngineV1alpha1Client) SecretRoleBindings(namespace string) SecretRoleBindingInterface {
	return newSecretRoleBindings(c, namespace)
}

func (c *EngineV1alpha1Client) SolrRoles(namespace string) SolrRoleInterface {
	return newSolrRoles(c, namespace)
}

func (c *EngineV1alpha1Client) WeaviateRoles(namespace string) WeaviateRoleInterface {
	return newWeaviateRoles(c, namespace)
}

func (c *EngineV1alpha1Client) ZooKeeperRoles(namespace string) ZooKeeperRoleInterface {
	return newZooKeeperRoles(c, namespace)
}

// NewForConfig creates a new EngineV1alpha1Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*EngineV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new EngineV1alpha1Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*EngineV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &EngineV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new EngineV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *EngineV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new EngineV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *EngineV1alpha1Client {
	return &EngineV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *EngineV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
