/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// Neo4jRolesGetter has a method to return a Neo4jRoleInterface.
// A group's client should implement this interface.
type Neo4jRolesGetter interface {
	Neo4jRoles(namespace string) Neo4jRoleInterface
}

// Neo4jRoleInterface has methods to work with Neo4jRole resources.
type Neo4jRoleInterface interface {
	Create(ctx context.Context, neo4jRole *enginev1alpha1.Neo4jRole, opts v1.CreateOptions) (*enginev1alpha1.Neo4jRole, error)
	Update(ctx context.Context, neo4jRole *enginev1alpha1.Neo4jRole, opts v1.UpdateOptions) (*enginev1alpha1.Neo4jRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, neo4jRole *enginev1alpha1.Neo4jRole, opts v1.UpdateOptions) (*enginev1alpha1.Neo4jRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*enginev1alpha1.Neo4jRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*enginev1alpha1.Neo4jRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *enginev1alpha1.Neo4jRole, err error)
	Neo4jRoleExpansion
}

// neo4jRoles implements Neo4jRoleInterface
type neo4jRoles struct {
	*gentype.ClientWithList[*enginev1alpha1.Neo4jRole, *enginev1alpha1.Neo4jRoleList]
}

// newNeo4jRoles returns a Neo4jRoles
func newNeo4jRoles(c *EngineV1alpha1Client, namespace string) *neo4jRoles {
	return &neo4jRoles{
		gentype.NewClientWithList[*enginev1alpha1.Neo4jRole, *enginev1alpha1.Neo4jRoleList](
			"neo4jroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *enginev1alpha1.Neo4jRole { return &enginev1alpha1.Neo4jRole{} },
			func() *enginev1alpha1.Neo4jRoleList { return &enginev1alpha1.Neo4jRoleList{} },
		),
	}
}
