/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PostgresRolesGetter has a method to return a PostgresRoleInterface.
// A group's client should implement this interface.
type PostgresRolesGetter interface {
	PostgresRoles(namespace string) PostgresRoleInterface
}

// PostgresRoleInterface has methods to work with PostgresRole resources.
type PostgresRoleInterface interface {
	Create(ctx context.Context, postgresRole *enginev1alpha1.PostgresRole, opts v1.CreateOptions) (*enginev1alpha1.PostgresRole, error)
	Update(ctx context.Context, postgresRole *enginev1alpha1.PostgresRole, opts v1.UpdateOptions) (*enginev1alpha1.PostgresRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, postgresRole *enginev1alpha1.PostgresRole, opts v1.UpdateOptions) (*enginev1alpha1.PostgresRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*enginev1alpha1.PostgresRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*enginev1alpha1.PostgresRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *enginev1alpha1.PostgresRole, err error)
	PostgresRoleExpansion
}

// postgresRoles implements PostgresRoleInterface
type postgresRoles struct {
	*gentype.ClientWithList[*enginev1alpha1.PostgresRole, *enginev1alpha1.PostgresRoleList]
}

// newPostgresRoles returns a PostgresRoles
func newPostgresRoles(c *EngineV1alpha1Client, namespace string) *postgresRoles {
	return &postgresRoles{
		gentype.NewClientWithList[*enginev1alpha1.PostgresRole, *enginev1alpha1.PostgresRoleList](
			"postgresroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *enginev1alpha1.PostgresRole { return &enginev1alpha1.PostgresRole{} },
			func() *enginev1alpha1.PostgresRoleList { return &enginev1alpha1.PostgresRoleList{} },
		),
	}
}
