/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// QdrantRolesGetter has a method to return a QdrantRoleInterface.
// A group's client should implement this interface.
type QdrantRolesGetter interface {
	QdrantRoles(namespace string) QdrantRoleInterface
}

// QdrantRoleInterface has methods to work with QdrantRole resources.
type QdrantRoleInterface interface {
	Create(ctx context.Context, qdrantRole *enginev1alpha1.QdrantRole, opts v1.CreateOptions) (*enginev1alpha1.QdrantRole, error)
	Update(ctx context.Context, qdrantRole *enginev1alpha1.QdrantRole, opts v1.UpdateOptions) (*enginev1alpha1.QdrantRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, qdrantRole *enginev1alpha1.QdrantRole, opts v1.UpdateOptions) (*enginev1alpha1.QdrantRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*enginev1alpha1.QdrantRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*enginev1alpha1.QdrantRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *enginev1alpha1.QdrantRole, err error)
	QdrantRoleExpansion
}

// qdrantRoles implements QdrantRoleInterface
type qdrantRoles struct {
	*gentype.ClientWithList[*enginev1alpha1.QdrantRole, *enginev1alpha1.QdrantRoleList]
}

// newQdrantRoles returns a QdrantRoles
func newQdrantRoles(c *EngineV1alpha1Client, namespace string) *qdrantRoles {
	return &qdrantRoles{
		gentype.NewClientWithList[*enginev1alpha1.QdrantRole, *enginev1alpha1.QdrantRoleList](
			"qdrantroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *enginev1alpha1.QdrantRole { return &enginev1alpha1.QdrantRole{} },
			func() *enginev1alpha1.QdrantRoleList { return &enginev1alpha1.QdrantRoleList{} },
		),
	}
}
