/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WeaviateRolesGetter has a method to return a WeaviateRoleInterface.
// A group's client should implement this interface.
type WeaviateRolesGetter interface {
	WeaviateRoles(namespace string) WeaviateRoleInterface
}

// WeaviateRoleInterface has methods to work with WeaviateRole resources.
type WeaviateRoleInterface interface {
	Create(ctx context.Context, weaviateRole *enginev1alpha1.WeaviateRole, opts v1.CreateOptions) (*enginev1alpha1.WeaviateRole, error)
	Update(ctx context.Context, weaviateRole *enginev1alpha1.WeaviateRole, opts v1.UpdateOptions) (*enginev1alpha1.WeaviateRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, weaviateRole *enginev1alpha1.WeaviateRole, opts v1.UpdateOptions) (*enginev1alpha1.WeaviateRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*enginev1alpha1.WeaviateRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*enginev1alpha1.WeaviateRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *enginev1alpha1.WeaviateRole, err error)
	WeaviateRoleExpansion
}

// weaviateRoles implements WeaviateRoleInterface
type weaviateRoles struct {
	*gentype.ClientWithList[*enginev1alpha1.WeaviateRole, *enginev1alpha1.WeaviateRoleList]
}

// newWeaviateRoles returns a WeaviateRoles
func newWeaviateRoles(c *EngineV1alpha1Client, namespace string) *weaviateRoles {
	return &weaviateRoles{
		gentype.NewClientWithList[*enginev1alpha1.WeaviateRole, *enginev1alpha1.WeaviateRoleList](
			"weaviateroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *enginev1alpha1.WeaviateRole { return &enginev1alpha1.WeaviateRole{} },
			func() *enginev1alpha1.WeaviateRoleList { return &enginev1alpha1.WeaviateRoleList{} },
		),
	}
}
