/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	enginev1alpha1 "kubevault.dev/apimachinery/apis/engine/v1alpha1"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ZooKeeperRolesGetter has a method to return a ZooKeeperRoleInterface.
// A group's client should implement this interface.
type ZooKeeperRolesGetter interface {
	ZooKeeperRoles(namespace string) ZooKeeperRoleInterface
}

// ZooKeeperRoleInterface has methods to work with ZooKeeperRole resources.
type ZooKeeperRoleInterface interface {
	Create(ctx context.Context, zooKeeperRole *enginev1alpha1.ZooKeeperRole, opts v1.CreateOptions) (*enginev1alpha1.ZooKeeperRole, error)
	Update(ctx context.Context, zooKeeperRole *enginev1alpha1.ZooKeeperRole, opts v1.UpdateOptions) (*enginev1alpha1.ZooKeeperRole, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, zooKeeperRole *enginev1alpha1.ZooKeeperRole, opts v1.UpdateOptions) (*enginev1alpha1.ZooKeeperRole, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*enginev1alpha1.ZooKeeperRole, error)
	List(ctx context.Context, opts v1.ListOptions) (*enginev1alpha1.ZooKeeperRoleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *enginev1alpha1.ZooKeeperRole, err error)
	ZooKeeperRoleExpansion
}

// zooKeeperRoles implements ZooKeeperRoleInterface
type zooKeeperRoles struct {
	*gentype.ClientWithList[*enginev1alpha1.ZooKeeperRole, *enginev1alpha1.ZooKeeperRoleList]
}

// newZooKeeperRoles returns a ZooKeeperRoles
func newZooKeeperRoles(c *EngineV1alpha1Client, namespace string) *zooKeeperRoles {
	return &zooKeeperRoles{
		gentype.NewClientWithList[*enginev1alpha1.ZooKeeperRole, *enginev1alpha1.ZooKeeperRoleList](
			"zookeeperroles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *enginev1alpha1.ZooKeeperRole { return &enginev1alpha1.ZooKeeperRole{} },
			func() *enginev1alpha1.ZooKeeperRoleList { return &enginev1alpha1.ZooKeeperRoleList{} },
		),
	}
}
