---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: awsaccesskeyrequests.secretengine.kubevault.com
spec:
  group: secretengine.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: AWSAccessKeyRequest
    plural: awsaccesskeyrequests
    singular: awsaccesskeyrequest
  scope: Namespaced
  validation:
    openAPIV3Schema: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
