---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: vault
  name: gcpaccesskeyrequests.engine.kubevault.com
spec:
  group: engine.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: GCPAccessKeyRequest
    plural: gcpaccesskeyrequests
    singular: gcpaccesskeyrequest
  scope: Namespaced
  validation:
    openAPIV3Schema: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
