apiVersion: catalog.kubevault.com/v1alpha1
kind: VaultServerVersion
metadata:
  name: "0.11.1"
  labels:
    app: vault-operator
spec:
  version: "0.11.1"
  deprecated: false
  vault:
    image: "vault:0.11.1"
  unsealer:
    image: "nightfury1204/vault-unsealer:prev"
  exporter:
    image: "sanjid/statsd-exporter:latest"
