/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	policyv1alpha1 "kubevault.dev/apimachinery/apis/policy/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VaultPolicyBindingLister helps list VaultPolicyBindings.
// All objects returned here must be treated as read-only.
type VaultPolicyBindingLister interface {
	// List lists all VaultPolicyBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policyv1alpha1.VaultPolicyBinding, err error)
	// VaultPolicyBindings returns an object that can list and get VaultPolicyBindings.
	VaultPolicyBindings(namespace string) VaultPolicyBindingNamespaceLister
	VaultPolicyBindingListerExpansion
}

// vaultPolicyBindingLister implements the VaultPolicyBindingLister interface.
type vaultPolicyBindingLister struct {
	listers.ResourceIndexer[*policyv1alpha1.VaultPolicyBinding]
}

// NewVaultPolicyBindingLister returns a new VaultPolicyBindingLister.
func NewVaultPolicyBindingLister(indexer cache.Indexer) VaultPolicyBindingLister {
	return &vaultPolicyBindingLister{listers.New[*policyv1alpha1.VaultPolicyBinding](indexer, policyv1alpha1.Resource("vaultpolicybinding"))}
}

// VaultPolicyBindings returns an object that can list and get VaultPolicyBindings.
func (s *vaultPolicyBindingLister) VaultPolicyBindings(namespace string) VaultPolicyBindingNamespaceLister {
	return vaultPolicyBindingNamespaceLister{listers.NewNamespaced[*policyv1alpha1.VaultPolicyBinding](s.ResourceIndexer, namespace)}
}

// VaultPolicyBindingNamespaceLister helps list and get VaultPolicyBindings.
// All objects returned here must be treated as read-only.
type VaultPolicyBindingNamespaceLister interface {
	// List lists all VaultPolicyBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policyv1alpha1.VaultPolicyBinding, err error)
	// Get retrieves the VaultPolicyBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*policyv1alpha1.VaultPolicyBinding, error)
	VaultPolicyBindingNamespaceListerExpansion
}

// vaultPolicyBindingNamespaceLister implements the VaultPolicyBindingNamespaceLister
// interface.
type vaultPolicyBindingNamespaceLister struct {
	listers.ResourceIndexer[*policyv1alpha1.VaultPolicyBinding]
}
