/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	v1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VaultRelaysGetter has a method to return a VaultRelayInterface.
// A group's client should implement this interface.
type VaultRelaysGetter interface {
	VaultRelays(namespace string) VaultRelayInterface
}

// VaultRelayInterface has methods to work with VaultRelay resources.
type VaultRelayInterface interface {
	Create(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.CreateOptions) (*v1alpha2.VaultRelay, error)
	Update(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.UpdateOptions) (*v1alpha2.VaultRelay, error)
	UpdateStatus(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.UpdateOptions) (*v1alpha2.VaultRelay, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha2.VaultRelay, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha2.VaultRelayList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.VaultRelay, err error)
	VaultRelayExpansion
}

// vaultAgents implements VaultRelayInterface
type vaultAgents struct {
	client rest.Interface
	ns     string
}

// newVaultRelays returns a VaultRelays
func newVaultRelays(c *KubevaultV1alpha2Client, namespace string) *vaultAgents {
	return &vaultAgents{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vaultAgent, and returns the corresponding vaultAgent object, and an error if there is any.
func (c *vaultAgents) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.VaultRelay, err error) {
	result = &v1alpha2.VaultRelay{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultrelays").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VaultRelays that match those selectors.
func (c *vaultAgents) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.VaultRelayList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha2.VaultRelayList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vaultrelays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vaultAgents.
func (c *vaultAgents) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vaultrelays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vaultAgent and creates it.  Returns the server's representation of the vaultAgent, and an error, if there is any.
func (c *vaultAgents) Create(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.CreateOptions) (result *v1alpha2.VaultRelay, err error) {
	result = &v1alpha2.VaultRelay{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vaultrelays").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultAgent).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vaultAgent and updates it. Returns the server's representation of the vaultAgent, and an error, if there is any.
func (c *vaultAgents) Update(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.UpdateOptions) (result *v1alpha2.VaultRelay, err error) {
	result = &v1alpha2.VaultRelay{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultrelays").
		Name(vaultAgent.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultAgent).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vaultAgents) UpdateStatus(ctx context.Context, vaultAgent *v1alpha2.VaultRelay, opts v1.UpdateOptions) (result *v1alpha2.VaultRelay, err error) {
	result = &v1alpha2.VaultRelay{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vaultrelays").
		Name(vaultAgent.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vaultAgent).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vaultAgent and deletes it. Returns an error if one occurs.
func (c *vaultAgents) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultrelays").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vaultAgents) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vaultrelays").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vaultAgent.
func (c *vaultAgents) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.VaultRelay, err error) {
	result = &v1alpha2.VaultRelay{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vaultrelays").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
