/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubevaultv1alpha2 "kubevault.dev/apimachinery/apis/kubevault/v1alpha2"
	scheme "kubevault.dev/apimachinery/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VaultRelaysGetter has a method to return a VaultRelayInterface.
// A group's client should implement this interface.
type VaultRelaysGetter interface {
	VaultRelays(namespace string) VaultRelayInterface
}

// VaultRelayInterface has methods to work with VaultRelay resources.
type VaultRelayInterface interface {
	Create(ctx context.Context, vaultRelay *kubevaultv1alpha2.VaultRelay, opts v1.CreateOptions) (*kubevaultv1alpha2.VaultRelay, error)
	Update(ctx context.Context, vaultRelay *kubevaultv1alpha2.VaultRelay, opts v1.UpdateOptions) (*kubevaultv1alpha2.VaultRelay, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, vaultRelay *kubevaultv1alpha2.VaultRelay, opts v1.UpdateOptions) (*kubevaultv1alpha2.VaultRelay, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubevaultv1alpha2.VaultRelay, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubevaultv1alpha2.VaultRelayList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubevaultv1alpha2.VaultRelay, err error)
	VaultRelayExpansion
}

// vaultRelays implements VaultRelayInterface
type vaultRelays struct {
	*gentype.ClientWithList[*kubevaultv1alpha2.VaultRelay, *kubevaultv1alpha2.VaultRelayList]
}

// newVaultRelays returns a VaultRelays
func newVaultRelays(c *KubevaultV1alpha2Client, namespace string) *vaultRelays {
	return &vaultRelays{
		gentype.NewClientWithList[*kubevaultv1alpha2.VaultRelay, *kubevaultv1alpha2.VaultRelayList](
			"vaultrelays",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubevaultv1alpha2.VaultRelay { return &kubevaultv1alpha2.VaultRelay{} },
			func() *kubevaultv1alpha2.VaultRelayList { return &kubevaultv1alpha2.VaultRelayList{} },
		),
	}
}
