apiVersion: admissionregistration.k8s.io/v1alpha1
kind: InitializerConfiguration
metadata:
  name: vault
initializers:
  # the name needs to be fully qualified, i.e., containing at least two "."
  - name: vault.initializer.kubernetes.io
    rules:
      # apiGroups, apiVersion, resources all support wildcard "*".
      # "*" cannot be mixed with non-wildcard.
      - apiGroups:
          - "*"
        apiVersions:
          - "*"
        resources:
          - daemonsets
          - deployments
          - jobs
          - replicasets
          - replicationcontrollers
          - statefulsets
