apiVersion: v1
kind: Service
metadata:
  name: {{ template "vault-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: "{{ template "vault-operator.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: pushgateway
    port: 56789
    protocol: TCP
    targetPort: pushgateway
  selector:
    app: "{{ template "vault-operator.name" . }}"
    release: "{{ .Release.Name }}"
