{{- if .Values.apiserver.enableValidatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.core.kube-vault.com
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "vault-operator.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
webhooks:
- name: vaultserver.admission.core.kube-vault.com
  clientConfig:
    service:
      namespace: default
      name: kubernetes
      path: /apis/admission.core.kube-vault.com/v1alpha1/vaultservers
    caBundle: {{ b64enc .Values.apiserver.ca }}
  rules:
  - operations:
    - CREATE
    - UPDATE
    apiGroups:
    - core.kube-vault.com
    apiVersions:
    - "*"
    resources:
    - restics
  failurePolicy: Fail
{{ end }}
