/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	opsv1alpha1 "kubevault.dev/apimachinery/apis/ops/v1alpha1"

	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// VaultOpsRequestLister helps list VaultOpsRequests.
// All objects returned here must be treated as read-only.
type VaultOpsRequestLister interface {
	// List lists all VaultOpsRequests in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.VaultOpsRequest, err error)
	// VaultOpsRequests returns an object that can list and get VaultOpsRequests.
	VaultOpsRequests(namespace string) VaultOpsRequestNamespaceLister
	VaultOpsRequestListerExpansion
}

// vaultOpsRequestLister implements the VaultOpsRequestLister interface.
type vaultOpsRequestLister struct {
	listers.ResourceIndexer[*opsv1alpha1.VaultOpsRequest]
}

// NewVaultOpsRequestLister returns a new VaultOpsRequestLister.
func NewVaultOpsRequestLister(indexer cache.Indexer) VaultOpsRequestLister {
	return &vaultOpsRequestLister{listers.New[*opsv1alpha1.VaultOpsRequest](indexer, opsv1alpha1.Resource("vaultopsrequest"))}
}

// VaultOpsRequests returns an object that can list and get VaultOpsRequests.
func (s *vaultOpsRequestLister) VaultOpsRequests(namespace string) VaultOpsRequestNamespaceLister {
	return vaultOpsRequestNamespaceLister{listers.NewNamespaced[*opsv1alpha1.VaultOpsRequest](s.ResourceIndexer, namespace)}
}

// VaultOpsRequestNamespaceLister helps list and get VaultOpsRequests.
// All objects returned here must be treated as read-only.
type VaultOpsRequestNamespaceLister interface {
	// List lists all VaultOpsRequests in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*opsv1alpha1.VaultOpsRequest, err error)
	// Get retrieves the VaultOpsRequest from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*opsv1alpha1.VaultOpsRequest, error)
	VaultOpsRequestNamespaceListerExpansion
}

// vaultOpsRequestNamespaceLister implements the VaultOpsRequestNamespaceLister
// interface.
type vaultOpsRequestNamespaceLister struct {
	listers.ResourceIndexer[*opsv1alpha1.VaultOpsRequest]
}
