{{ if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ template "steward.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "{{ template "steward.name" . }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs: ["get", "create"]
- apiGroups:
  - steward.appscode.com
  resources:
  - restics
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - replicasets
  - daemonsets
  verbs: ["list", "watch", "update"]
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs: ["list", "watch", "update"]
- apiGroups: [""]
  resources:
  - namespaces
  - replicationcontrollers
  verbs: ["list", "watch", "update"]
- apiGroups: [""]
  resources:
  - secrets
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create"]
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", delete"]
{{ end }}
